package runtime

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

//go:embed capabilities/claude.yaml
var claudeCapabilitiesYAML []byte

// ClaudeAdapter implements the Adapter interface for Claude Code.
// It reads from .leo/ and generates .claude/CLAUDE.md + settings.json.
type ClaudeAdapter struct {
	projectRoot string
}

// NewClaudeAdapter creates a ClaudeAdapter for the given project root.
func NewClaudeAdapter(projectRoot string) *ClaudeAdapter {
	return &ClaudeAdapter{projectRoot: projectRoot}
}

func (a *ClaudeAdapter) Name() string {
	return "claude"
}

func (a *ClaudeAdapter) GenerateContextFile(config Config, constraints []Constraint, skills []Skill, identity *Identity) error {
	claudeDir := filepath.Join(a.projectRoot, ".claude")
	if err := os.MkdirAll(claudeDir, 0755); err != nil {
		return fmt.Errorf("creating .claude dir: %w", err)
	}

	content := a.Watermark() + "\n\n" + BuildContextContent(config, constraints, skills, identity)

	contextFile := filepath.Join(claudeDir, "CLAUDE.md")
	if err := os.WriteFile(contextFile, []byte(content), 0644); err != nil {
		return fmt.Errorf("writing CLAUDE.md: %w", err)
	}

	return nil
}

func (a *ClaudeAdapter) SupportsHooks() bool {
	return true
}

func (a *ClaudeAdapter) RegisterHooks(hooks []HookDef) error {
	claudeDir := filepath.Join(a.projectRoot, ".claude")
	settingsPath := filepath.Join(claudeDir, "settings.json")

	// Load existing settings or start fresh.
	settings := make(map[string]any)
	if data, err := os.ReadFile(settingsPath); err == nil {
		if err := json.Unmarshal(data, &settings); err != nil {
			return fmt.Errorf("parsing settings.json: %w", err)
		}
	}

	// Build hooks structure.
	hooksList := make([]map[string]any, 0, len(hooks))
	for _, h := range hooks {
		hook := map[string]any{
			"type":    h.Event,
			"command": h.Command,
		}
		if h.Matcher != "" {
			hook["matcher"] = h.Matcher
		}
		hooksList = append(hooksList, hook)
	}

	settings["hooks"] = hooksList

	data, err := json.MarshalIndent(settings, "", "  ")
	if err != nil {
		return fmt.Errorf("marshaling settings: %w", err)
	}

	data = append(data, '\n')
	if err := os.WriteFile(settingsPath, data, 0644); err != nil {
		return fmt.Errorf("writing settings.json: %w", err)
	}

	return nil
}

func (a *ClaudeAdapter) DetectRuntime() bool {
	info, err := os.Stat(filepath.Join(a.projectRoot, ".claude"))
	return err == nil && info.IsDir()
}

func (a *ClaudeAdapter) GeneratedFiles() []string {
	return []string{
		filepath.Join(".claude", "CLAUDE.md"),
		filepath.Join(".claude", "settings.json"),
	}
}

func (a *ClaudeAdapter) GeneratedDirs() []string {
	return []string{".claude"}
}

func (a *ClaudeAdapter) Watermark() string {
	return "<!-- Generated by L.E.O. — do not edit manually -->"
}

func (a *ClaudeAdapter) DefaultTierMapping() map[string]string {
	return map[string]string{
		"orchestration": "opus",
		"execution":     "sonnet",
		"review":        "sonnet",
	}
}

func (a *ClaudeAdapter) Capabilities() AdapterCapability {
	var cap AdapterCapability
	if err := yaml.Unmarshal(claudeCapabilitiesYAML, &cap); err != nil {
		// Fallback: return minimal capability if YAML is malformed.
		return AdapterCapability{Name: "claude-code", Version: "1.0"}
	}
	return cap
}

// HasWatermark checks if a file contains the L.E.O. watermark.
func HasWatermark(path string) bool {
	data, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	return strings.Contains(string(data), "Generated by L.E.O.")
}

// BackupIfNeeded creates a .bkp copy of a file if it exists and was NOT
// generated by L.E.O. (i.e., it's a user file). Returns true if a backup
// was created.
func BackupIfNeeded(path string) (bool, error) {
	if _, err := os.Stat(path); err != nil {
		return false, nil // file doesn't exist, no backup needed
	}

	if HasWatermark(path) {
		return false, nil // it's ours, overwrite freely
	}

	data, err := os.ReadFile(path)
	if err != nil {
		return false, fmt.Errorf("reading file for backup: %w", err)
	}

	bkpPath := path + ".bkp"
	if err := os.WriteFile(bkpPath, data, 0644); err != nil {
		return false, fmt.Errorf("writing backup: %w", err)
	}

	return true, nil
}
