package runtime

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestClaudeAdapter_Name(t *testing.T) {
	a := NewClaudeAdapter("/tmp/test")
	if a.Name() != "claude" {
		t.Errorf("expected %q, got %q", "claude", a.Name())
	}
}

func TestClaudeAdapter_SupportsHooks(t *testing.T) {
	a := NewClaudeAdapter("/tmp/test")
	if !a.SupportsHooks() {
		t.Error("expected SupportsHooks to be true")
	}
}

func TestClaudeAdapter_DetectRuntime(t *testing.T) {
	dir := t.TempDir()

	a := NewClaudeAdapter(dir)
	if a.DetectRuntime() {
		t.Error("expected false when .claude/ does not exist")
	}

	os.MkdirAll(filepath.Join(dir, ".claude"), 0755)
	if !a.DetectRuntime() {
		t.Error("expected true when .claude/ exists")
	}
}

func TestClaudeAdapter_GenerateContextFile(t *testing.T) {
	dir := t.TempDir()
	a := NewClaudeAdapter(dir)

	config := Config{
		Version: "1",
		User: UserConfig{
			Language:          "en",
			Autonomy:          "balanced",
			CommunicationMode: "concise",
		},
	}

	constraints := []Constraint{
		{ID: "anti-hallucination", Summary: "When unsure, say you don't know."},
	}

	skills := []Skill{
		{ID: "session-wrap-up", Summary: "End-of-session knowledge propagation."},
	}

	identity := &Identity{
		What: "MOM — a living knowledge infrastructure.",
	}

	if err := a.GenerateContextFile(config, constraints, skills, identity); err != nil {
		t.Fatalf("GenerateContextFile failed: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(dir, ".claude", "CLAUDE.md"))
	if err != nil {
		t.Fatalf("reading CLAUDE.md: %v", err)
	}

	s := string(content)
	checks := []string{
		"Generated by MOM",
		"MOM — Memory Oriented Machine",
		"living knowledge infrastructure",
		"## Constraints",
		"anti-hallucination",
		"When unsure, say you don't know.",
		"## Skills",
		"session-wrap-up",
		"End-of-session knowledge propagation.",
		"must be written in English",
		"## Communication mode: Concise",
		"no filler",
		"Balanced",
		"Propose before",
		"## Knowledge base",
		"## During work",
	}
	for _, check := range checks {
		if !strings.Contains(s, check) {
			t.Errorf("CLAUDE.md missing %q", check)
		}
	}
}

// TestClaudeAdapter_GenerateContextFile_NoProfile verifies that retired profile
// references (orchestrator, specialist, delegation) do NOT appear in generated output.
func TestClaudeAdapter_GenerateContextFile_NoProfile(t *testing.T) {
	dir := t.TempDir()
	a := NewClaudeAdapter(dir)

	config := Config{
		Version: "1",
		User:    UserConfig{Language: "en", Autonomy: "balanced", CommunicationMode: "concise"},
	}

	if err := a.GenerateContextFile(config, nil, nil, nil); err != nil {
		t.Fatalf("GenerateContextFile failed: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(dir, ".claude", "CLAUDE.md"))
	if err != nil {
		t.Fatalf("reading CLAUDE.md: %v", err)
	}

	s := string(content)
	// These phrases indicate the retired orchestration model — they must not appear.
	forbidden := []string{"specialist", "delegation", "task-intake", "Active Profile",
		"orchestrates, never executes", "leo orchestrates", "task pipeline"}
	for _, bad := range forbidden {
		if strings.Contains(strings.ToLower(s), strings.ToLower(bad)) {
			t.Errorf("CLAUDE.md must not contain %q", bad)
		}
	}
}

func TestClaudeAdapter_GenerateContextFile_NoIdentity(t *testing.T) {
	dir := t.TempDir()
	a := NewClaudeAdapter(dir)

	config := Config{
		Version: "1",
		User: UserConfig{
			Language: "en",
			Autonomy: "balanced",
		},
	}

	if err := a.GenerateContextFile(config, nil, nil, nil); err != nil {
		t.Fatalf("GenerateContextFile failed: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(dir, ".claude", "CLAUDE.md"))
	if err != nil {
		t.Fatalf("reading CLAUDE.md: %v", err)
	}

	s := string(content)
	if !strings.Contains(s, "You are MOM") {
		t.Error("CLAUDE.md missing fallback identity text")
	}
}

func TestClaudeAdapter_GenerateContextFile_CommunicationModes(t *testing.T) {
	modes := []struct {
		mode string
		want string
	}{
		{"concise", "## Communication mode: Concise"},
		{"normal", "## Communication mode: Normal"},
		{"verbose", "## Communication mode: Verbose"},
		{"caveman", "## Communication mode: Caveman"},
	}

	for _, tc := range modes {
		t.Run(tc.mode, func(t *testing.T) {
			dir := t.TempDir()
			a := NewClaudeAdapter(dir)
			cfg := Config{
				Version: "1",
				User:    UserConfig{Language: "en", Autonomy: "balanced", CommunicationMode: tc.mode},
			}
			if err := a.GenerateContextFile(cfg, nil, nil, nil); err != nil {
				t.Fatalf("GenerateContextFile failed: %v", err)
			}
			content, _ := os.ReadFile(filepath.Join(dir, ".claude", "CLAUDE.md"))
			if !strings.Contains(string(content), tc.want) {
				t.Errorf("CLAUDE.md missing %q for mode %q", tc.want, tc.mode)
			}
		})
	}
}

func TestClaudeAdapter_RegisterHooks(t *testing.T) {
	dir := t.TempDir()
	os.MkdirAll(filepath.Join(dir, ".claude"), 0755)
	a := NewClaudeAdapter(dir)

	hooks := []HookDef{
		{Event: "PostToolUse", Matcher: "Write", Command: "validate.sh"},
	}

	if err := a.RegisterHooks(hooks); err != nil {
		t.Fatalf("RegisterHooks failed: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(dir, ".claude", "settings.json"))
	if err != nil {
		t.Fatalf("reading settings.json: %v", err)
	}

	s := string(content)
	if !strings.Contains(s, "PostToolUse") {
		t.Error("settings.json missing hook event")
	}
	if !strings.Contains(s, "validate.sh") {
		t.Error("settings.json missing hook command")
	}
}

func TestClaudeAdapter_Watermark(t *testing.T) {
	a := NewClaudeAdapter("/tmp/test")
	wm := a.Watermark()
	if !strings.Contains(wm, "Generated by MOM") {
		t.Errorf("expected watermark to contain 'Generated by MOM', got %q", wm)
	}
}

func TestClaudeAdapter_DefaultTierMapping(t *testing.T) {
	a := NewClaudeAdapter("/tmp/test")
	tiers := a.DefaultTierMapping()

	expected := map[string]string{
		"orchestration": "opus",
		"execution":     "sonnet",
		"review":        "sonnet",
	}

	for k, v := range expected {
		if tiers[k] != v {
			t.Errorf("tier %q: expected %q, got %q", k, v, tiers[k])
		}
	}
}

func TestWatermarkPresent(t *testing.T) {
	dir := t.TempDir()
	a := NewClaudeAdapter(dir)

	config := Config{Version: "1", User: UserConfig{Language: "en", Autonomy: "balanced"}}

	if err := a.GenerateContextFile(config, nil, nil, nil); err != nil {
		t.Fatalf("GenerateContextFile failed: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(dir, ".claude", "CLAUDE.md"))
	if err != nil {
		t.Fatal(err)
	}

	if !strings.HasPrefix(string(content), "<!-- Generated by MOM") {
		t.Error("generated file should start with watermark")
	}
}

func TestBackupCreatedForUserFile(t *testing.T) {
	dir := t.TempDir()
	userFile := filepath.Join(dir, "CLAUDE.md")
	os.WriteFile(userFile, []byte("# My custom rules"), 0644)

	backed, err := BackupIfNeeded(userFile)
	if err != nil {
		t.Fatalf("BackupIfNeeded failed: %v", err)
	}
	if !backed {
		t.Error("expected backup to be created for user file")
	}

	bkpContent, err := os.ReadFile(userFile + ".bkp")
	if err != nil {
		t.Fatal("backup file not created")
	}
	if string(bkpContent) != "# My custom rules" {
		t.Error("backup content doesn't match original")
	}
}

func TestNoBackupForLeoFile(t *testing.T) {
	dir := t.TempDir()
	leoFile := filepath.Join(dir, "CLAUDE.md")
	os.WriteFile(leoFile, []byte("<!-- Generated by MOM — do not edit manually -->\n# MOM"), 0644)

	backed, err := BackupIfNeeded(leoFile)
	if err != nil {
		t.Fatalf("BackupIfNeeded failed: %v", err)
	}
	if backed {
		t.Error("should not backup Leo-generated file")
	}
}

func TestBackupNonexistentFile(t *testing.T) {
	backed, err := BackupIfNeeded("/nonexistent/path")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if backed {
		t.Error("should not backup nonexistent file")
	}
}
