package runtime

import (
	_ "embed"
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

//go:embed capabilities/cline.yaml
var clineCapabilitiesYAML []byte

// ClineAdapter implements the Adapter interface for Cline.
// It reads from .leo/ and generates .clinerules/leo-context.md.
type ClineAdapter struct {
	projectRoot string
}

// NewClineAdapter creates a ClineAdapter for the given project root.
func NewClineAdapter(projectRoot string) *ClineAdapter {
	return &ClineAdapter{projectRoot: projectRoot}
}

func (a *ClineAdapter) Name() string {
	return "cline"
}

func (a *ClineAdapter) GenerateContextFile(config Config, constraints []Constraint, skills []Skill, identity *Identity) error {
	rulesDir := filepath.Join(a.projectRoot, ".clinerules")
	if err := os.MkdirAll(rulesDir, 0755); err != nil {
		return fmt.Errorf("creating .clinerules dir: %w", err)
	}

	content := a.Watermark() + "\n\n" + BuildContextContent(config, constraints, skills, identity)

	contextFile := filepath.Join(rulesDir, "leo-context.md")
	if err := os.WriteFile(contextFile, []byte(content), 0644); err != nil {
		return fmt.Errorf("writing leo-context.md: %w", err)
	}

	return nil
}

func (a *ClineAdapter) SupportsHooks() bool {
	return false
}

func (a *ClineAdapter) RegisterHooks(hooks []HookDef) error {
	return nil
}

func (a *ClineAdapter) DetectRuntime() bool {
	info, err := os.Stat(filepath.Join(a.projectRoot, ".clinerules"))
	return err == nil && info.IsDir()
}

func (a *ClineAdapter) GeneratedFiles() []string {
	return []string{filepath.Join(".clinerules", "leo-context.md")}
}

// GeneratedDirs returns nil — .clinerules/ may contain user's workflows, hooks,
// and custom rules. Uninstall never removes the directory, only leo-context.md.
func (a *ClineAdapter) GeneratedDirs() []string {
	return nil
}

func (a *ClineAdapter) Watermark() string {
	return "<!-- Generated by L.E.O. — do not edit manually -->"
}

// DefaultTierMapping returns nil — Cline supports multiple providers.
// Model selection happens in Cline's UI, not in generated instructions.
func (a *ClineAdapter) DefaultTierMapping() map[string]string {
	return nil
}

func (a *ClineAdapter) Capabilities() AdapterCapability {
	var cap AdapterCapability
	if err := yaml.Unmarshal(clineCapabilitiesYAML, &cap); err != nil {
		return AdapterCapability{Name: "cline", Version: "0.1"}
	}
	return cap
}
