package runtime

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestClineAdapter_Name(t *testing.T) {
	a := NewClineAdapter("/tmp/test")
	if a.Name() != "cline" {
		t.Errorf("expected %q, got %q", "cline", a.Name())
	}
}

func TestClineAdapter_DetectRuntime(t *testing.T) {
	dir := t.TempDir()
	a := NewClineAdapter(dir)

	if a.DetectRuntime() {
		t.Error("expected false when .clinerules/ does not exist")
	}

	os.MkdirAll(filepath.Join(dir, ".clinerules"), 0755)
	if !a.DetectRuntime() {
		t.Error("expected true when .clinerules/ exists")
	}
}

func TestClineAdapter_GenerateContextFile(t *testing.T) {
	dir := t.TempDir()
	a := NewClineAdapter(dir)

	config := Config{
		Version:  "1",
		Delivery: "context-file",
		User:     UserConfig{Language: "en", Autonomy: "balanced", CommunicationMode: "concise"},
	}
	constraints := []Constraint{{ID: "anti-hallucination", Summary: "Don't guess."}}
	skills := []Skill{{ID: "session-wrap-up", Summary: "End-of-session."}}
	identity := &Identity{What: "MOM — a living knowledge infrastructure."}

	if err := a.GenerateContextFile(config, constraints, skills, identity); err != nil {
		t.Fatalf("GenerateContextFile failed: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(dir, ".clinerules", "mom-context.md"))
	if err != nil {
		t.Fatalf("reading mom-context.md: %v", err)
	}

	s := string(content)
	checks := []string{
		"Generated by MOM",
		"MOM — Memory Oriented Machine",
		"anti-hallucination",
		"session-wrap-up",
	}
	for _, check := range checks {
		if !strings.Contains(s, check) {
			t.Errorf("mom-context.md missing %q", check)
		}
	}
}

func TestClineAdapter_GenerateContextFileCreatesDir(t *testing.T) {
	dir := t.TempDir()
	a := NewClineAdapter(dir)

	config := Config{Version: "1", User: UserConfig{Language: "en", Autonomy: "balanced"}}

	if err := a.GenerateContextFile(config, nil, nil, nil); err != nil {
		t.Fatal(err)
	}

	info, err := os.Stat(filepath.Join(dir, ".clinerules"))
	if err != nil {
		t.Fatal(".clinerules/ dir not created")
	}
	if !info.IsDir() {
		t.Error("expected .clinerules/ to be a directory")
	}
}

func TestClineAdapter_GenerateContextFilePreservesDir(t *testing.T) {
	dir := t.TempDir()
	rulesDir := filepath.Join(dir, ".clinerules")
	os.MkdirAll(rulesDir, 0755)

	// Create a user file in .clinerules/
	userFile := filepath.Join(rulesDir, "my-rule.md")
	os.WriteFile(userFile, []byte("# My custom rule"), 0644)

	a := NewClineAdapter(dir)
	config := Config{Version: "1", User: UserConfig{Language: "en", Autonomy: "balanced"}}

	if err := a.GenerateContextFile(config, nil, nil, nil); err != nil {
		t.Fatal(err)
	}

	// User file should still exist
	content, err := os.ReadFile(userFile)
	if err != nil {
		t.Fatal("user file was removed")
	}
	if string(content) != "# My custom rule" {
		t.Error("user file content changed")
	}
}

func TestClineAdapter_GeneratedFiles(t *testing.T) {
	a := NewClineAdapter("/tmp/test")
	files := a.GeneratedFiles()

	want := []string{
		filepath.Join(".clinerules", "mom-context.md"),
		filepath.Join(".clinerules", "hooks", "task-complete.sh"),
		filepath.Join(".clinerules", "hooks", "task-cancel.sh"),
		".mcp.json",
	}

	if len(files) != len(want) {
		t.Fatalf("GeneratedFiles() returned %d files, want %d", len(files), len(want))
	}

	for i, f := range files {
		if f != want[i] {
			t.Errorf("GeneratedFiles()[%d] = %q, want %q", i, f, want[i])
		}
	}
}

func TestClineAdapter_GeneratedDirs(t *testing.T) {
	a := NewClineAdapter("/tmp/test")
	if dirs := a.GeneratedDirs(); dirs != nil {
		t.Errorf("expected nil dirs (conservative uninstall), got %v", dirs)
	}
}

func TestClineAdapter_SupportsHooks(t *testing.T) {
	a := NewClineAdapter("/tmp/test")
	if !a.SupportsHooks() {
		t.Error("expected SupportsHooks to be true")
	}
}

func TestClineAdapter_NoIdentity(t *testing.T) {
	dir := t.TempDir()
	a := NewClineAdapter(dir)

	config := Config{Version: "1", Delivery: "context-file", User: UserConfig{Language: "en", Autonomy: "balanced"}}

	if err := a.GenerateContextFile(config, nil, nil, nil); err != nil {
		t.Fatal(err)
	}

	content, _ := os.ReadFile(filepath.Join(dir, ".clinerules", "mom-context.md"))
	if !strings.Contains(string(content), "She remembers, so you don't have to") {
		t.Error("should have fallback identity")
	}
}

func TestClineAdapter_RegisterHooks(t *testing.T) {
	dir := t.TempDir()
	adapter := NewClineAdapter(dir)

	if err := adapter.RegisterHooks(ClineHooks()); err != nil {
		t.Fatalf("RegisterHooks() error: %v", err)
	}

	for _, name := range []string{"task-complete.sh", "task-cancel.sh"} {
		path := filepath.Join(dir, ".clinerules", "hooks", name)
		if _, err := os.Stat(path); err != nil {
			t.Errorf("expected hook script %s to exist, got: %v", name, err)
		}
	}
}

func TestClineAdapter_HookScriptContent(t *testing.T) {
	dir := t.TempDir()
	adapter := NewClineAdapter(dir)

	if err := adapter.RegisterHooks(ClineHooks()); err != nil {
		t.Fatalf("RegisterHooks() error: %v", err)
	}

	scriptPath := filepath.Join(dir, ".clinerules", "hooks", "task-complete.sh")
	data, err := os.ReadFile(scriptPath)
	if err != nil {
		t.Fatalf("reading task-complete.sh: %v", err)
	}
	content := string(data)

	for _, want := range []string{"mom record", "mom draft", `{"cancel": false}`} {
		if !strings.Contains(content, want) {
			t.Errorf("task-complete.sh should contain %q, got:\n%s", want, content)
		}
	}

	if !strings.HasPrefix(content, "#!/bin/sh\n") {
		t.Errorf("task-complete.sh should start with shebang, got:\n%s", content)
	}
}

func TestClineAdapter_HookScriptPermissions(t *testing.T) {
	dir := t.TempDir()
	adapter := NewClineAdapter(dir)

	if err := adapter.RegisterHooks(ClineHooks()); err != nil {
		t.Fatalf("RegisterHooks() error: %v", err)
	}

	for _, name := range []string{"task-complete.sh", "task-cancel.sh"} {
		path := filepath.Join(dir, ".clinerules", "hooks", name)
		info, err := os.Stat(path)
		if err != nil {
			t.Fatalf("stat %s: %v", name, err)
		}
		perm := info.Mode().Perm()
		if perm&0111 == 0 {
			t.Errorf("%s should be executable, got permissions %o", name, perm)
		}
	}
}

func TestClineAdapter_RegisterMCP(t *testing.T) {
	dir := t.TempDir()
	adapter := NewClineAdapter(dir)

	if err := adapter.RegisterMCP(); err != nil {
		t.Fatalf("RegisterMCP() error: %v", err)
	}

	mcpPath := filepath.Join(dir, ".mcp.json")
	data, err := os.ReadFile(mcpPath)
	if err != nil {
		t.Fatalf("reading .mcp.json: %v", err)
	}

	var root map[string]any
	if err := json.Unmarshal(data, &root); err != nil {
		t.Fatalf("parsing .mcp.json: %v", err)
	}

	servers, ok := root["mcpServers"].(map[string]any)
	if !ok {
		t.Fatalf("expected mcpServers key in .mcp.json")
	}

	mom, ok := servers["mom"].(map[string]any)
	if !ok {
		t.Fatalf("expected mom entry in mcpServers")
	}

	if mom["command"] != "mom" {
		t.Errorf("expected command=mom, got %v", mom["command"])
	}
}

func TestClineEventToFilename(t *testing.T) {
	tests := []struct {
		input string
		want  string
	}{
		{"TaskComplete", "task-complete.sh"},
		{"TaskCancel", "task-cancel.sh"},
	}

	for _, tt := range tests {
		got := clineEventToFilename(tt.input)
		if got != tt.want {
			t.Errorf("clineEventToFilename(%q) = %q, want %q", tt.input, got, tt.want)
		}
	}
}

func TestClineUninstallRemovesOnlyMomFile(t *testing.T) {
	dir := t.TempDir()
	rulesDir := filepath.Join(dir, ".clinerules")
	os.MkdirAll(rulesDir, 0755)

	// Create user file and leo file
	os.WriteFile(filepath.Join(rulesDir, "my-rule.md"), []byte("# Custom"), 0644)
	os.WriteFile(filepath.Join(rulesDir, "mom-context.md"), []byte("<!-- Generated by MOM -->"), 0644)

	a := NewClineAdapter(dir)

	// Simulate uninstall: remove generated files
	for _, f := range a.GeneratedFiles() {
		os.Remove(filepath.Join(dir, f))
	}

	// mom-context.md should be gone
	if _, err := os.Stat(filepath.Join(rulesDir, "mom-context.md")); err == nil {
		t.Error("mom-context.md should have been removed")
	}

	// my-rule.md should still exist
	if _, err := os.Stat(filepath.Join(rulesDir, "my-rule.md")); err != nil {
		t.Error("user file should still exist")
	}

	// .clinerules/ should still exist (GeneratedDirs returns nil)
	if _, err := os.Stat(rulesDir); err != nil {
		t.Error(".clinerules/ directory should still exist")
	}
}
