package runtime

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestClineAdapter_Name(t *testing.T) {
	a := NewClineAdapter("/tmp/test")
	if a.Name() != "cline" {
		t.Errorf("expected %q, got %q", "cline", a.Name())
	}
}

func TestClineAdapter_DetectRuntime(t *testing.T) {
	dir := t.TempDir()
	a := NewClineAdapter(dir)

	if a.DetectRuntime() {
		t.Error("expected false when .clinerules/ does not exist")
	}

	os.MkdirAll(filepath.Join(dir, ".clinerules"), 0755)
	if !a.DetectRuntime() {
		t.Error("expected true when .clinerules/ exists")
	}
}

func TestClineAdapter_GenerateContextFile(t *testing.T) {
	dir := t.TempDir()
	a := NewClineAdapter(dir)

	config := Config{
		Version: "1",
		User:    UserConfig{Language: "en", Mode: "concise", Autonomy: "balanced"},
	}
	profile := Profile{Name: "CTO", Description: "Architecture, scalability"}
	constraints := []Constraint{{ID: "anti-hallucination", Summary: "Don't guess."}}
	skills := []Skill{{ID: "session-wrap-up", Summary: "End-of-session."}}
	identity := &Identity{What: "L.E.O. — a living knowledge infrastructure."}

	if err := a.GenerateContextFile(config, profile, constraints, skills, identity); err != nil {
		t.Fatalf("GenerateContextFile failed: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(dir, ".clinerules", "leo-context.md"))
	if err != nil {
		t.Fatalf("reading leo-context.md: %v", err)
	}

	s := string(content)
	checks := []string{
		"Generated by L.E.O.",
		"LEO — Living Ecosystem Orchestrator",
		"CTO",
		"anti-hallucination",
		"session-wrap-up",
	}
	for _, check := range checks {
		if !strings.Contains(s, check) {
			t.Errorf("leo-context.md missing %q", check)
		}
	}
}

func TestClineAdapter_GenerateContextFileCreatesDir(t *testing.T) {
	dir := t.TempDir()
	a := NewClineAdapter(dir)

	config := Config{Version: "1", User: UserConfig{Language: "en", Mode: "concise", Autonomy: "balanced"}}
	profile := Profile{Name: "Test", Description: "Test"}

	if err := a.GenerateContextFile(config, profile, nil, nil, nil); err != nil {
		t.Fatal(err)
	}

	info, err := os.Stat(filepath.Join(dir, ".clinerules"))
	if err != nil {
		t.Fatal(".clinerules/ dir not created")
	}
	if !info.IsDir() {
		t.Error("expected .clinerules/ to be a directory")
	}
}

func TestClineAdapter_GenerateContextFilePreservesDir(t *testing.T) {
	dir := t.TempDir()
	rulesDir := filepath.Join(dir, ".clinerules")
	os.MkdirAll(rulesDir, 0755)

	// Create a user file in .clinerules/
	userFile := filepath.Join(rulesDir, "my-rule.md")
	os.WriteFile(userFile, []byte("# My custom rule"), 0644)

	a := NewClineAdapter(dir)
	config := Config{Version: "1", User: UserConfig{Language: "en", Mode: "concise", Autonomy: "balanced"}}
	profile := Profile{Name: "Test", Description: "Test"}

	if err := a.GenerateContextFile(config, profile, nil, nil, nil); err != nil {
		t.Fatal(err)
	}

	// User file should still exist
	content, err := os.ReadFile(userFile)
	if err != nil {
		t.Fatal("user file was removed")
	}
	if string(content) != "# My custom rule" {
		t.Error("user file content changed")
	}
}

func TestClineAdapter_GeneratedFiles(t *testing.T) {
	a := NewClineAdapter("/tmp/test")
	files := a.GeneratedFiles()
	if len(files) != 1 || files[0] != filepath.Join(".clinerules", "leo-context.md") {
		t.Errorf("expected [.clinerules/leo-context.md], got %v", files)
	}
}

func TestClineAdapter_GeneratedDirs(t *testing.T) {
	a := NewClineAdapter("/tmp/test")
	if dirs := a.GeneratedDirs(); dirs != nil {
		t.Errorf("expected nil dirs (conservative uninstall), got %v", dirs)
	}
}

func TestClineAdapter_SupportsHooks(t *testing.T) {
	a := NewClineAdapter("/tmp/test")
	if a.SupportsHooks() {
		t.Error("expected SupportsHooks to be false")
	}
}

func TestClineAdapter_DefaultTierMapping(t *testing.T) {
	a := NewClineAdapter("/tmp/test")
	if tiers := a.DefaultTierMapping(); tiers != nil {
		t.Errorf("expected nil tier mapping for cline, got %v", tiers)
	}
}

func TestClineAdapter_NoIdentity(t *testing.T) {
	dir := t.TempDir()
	a := NewClineAdapter(dir)

	config := Config{Version: "1", User: UserConfig{Language: "en", Mode: "concise", Autonomy: "balanced"}}
	profile := Profile{Name: "Test", Description: "Test"}

	if err := a.GenerateContextFile(config, profile, nil, nil, nil); err != nil {
		t.Fatal(err)
	}

	content, _ := os.ReadFile(filepath.Join(dir, ".clinerules", "leo-context.md"))
	if !strings.Contains(string(content), "You are LEO") {
		t.Error("should have fallback identity")
	}
}

func TestClineUninstallRemovesOnlyLeoFile(t *testing.T) {
	dir := t.TempDir()
	rulesDir := filepath.Join(dir, ".clinerules")
	os.MkdirAll(rulesDir, 0755)

	// Create user file and leo file
	os.WriteFile(filepath.Join(rulesDir, "my-rule.md"), []byte("# Custom"), 0644)
	os.WriteFile(filepath.Join(rulesDir, "leo-context.md"), []byte("<!-- Generated by L.E.O. -->"), 0644)

	a := NewClineAdapter(dir)

	// Simulate uninstall: remove generated files
	for _, f := range a.GeneratedFiles() {
		os.Remove(filepath.Join(dir, f))
	}

	// leo-context.md should be gone
	if _, err := os.Stat(filepath.Join(rulesDir, "leo-context.md")); err == nil {
		t.Error("leo-context.md should have been removed")
	}

	// my-rule.md should still exist
	if _, err := os.Stat(filepath.Join(rulesDir, "my-rule.md")); err != nil {
		t.Error("user file should still exist")
	}

	// .clinerules/ should still exist (GeneratedDirs returns nil)
	if _, err := os.Stat(rulesDir); err != nil {
		t.Error(".clinerules/ directory should still exist")
	}
}
