package runtime

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestCodexAdapter_Name(t *testing.T) {
	a := NewCodexAdapter("/tmp/test")
	if a.Name() != "codex" {
		t.Errorf("expected %q, got %q", "codex", a.Name())
	}
}

func TestCodexAdapter_DetectRuntime(t *testing.T) {
	dir := t.TempDir()
	a := NewCodexAdapter(dir)

	if a.DetectRuntime() {
		t.Error("expected false when AGENTS.md does not exist")
	}

	os.WriteFile(filepath.Join(dir, "AGENTS.md"), []byte("# agents"), 0644)
	if !a.DetectRuntime() {
		t.Error("expected true when AGENTS.md exists")
	}
}

func TestCodexAdapter_GenerateContextFile(t *testing.T) {
	dir := t.TempDir()
	a := NewCodexAdapter(dir)

	config := Config{
		Version:  "1",
		Delivery: "context-file",
		User:     UserConfig{Language: "en", Autonomy: "balanced", CommunicationMode: "concise"},
	}
	constraints := []Constraint{{ID: "anti-hallucination", Summary: "Don't guess."}}
	skills := []Skill{{ID: "session-wrap-up", Summary: "End-of-session."}}
	identity := &Identity{What: "MOM — a living knowledge infrastructure."}

	if err := a.GenerateContextFile(config, constraints, skills, identity); err != nil {
		t.Fatalf("GenerateContextFile failed: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(dir, "AGENTS.md"))
	if err != nil {
		t.Fatalf("reading AGENTS.md: %v", err)
	}

	s := string(content)
	checks := []string{
		"Generated by MOM",
		"MOM — Memory Oriented Machine",
		"anti-hallucination",
		"session-wrap-up",
		"## Memory",
	}
	for _, check := range checks {
		if !strings.Contains(s, check) {
			t.Errorf("AGENTS.md missing %q", check)
		}
	}
}

func TestCodexAdapter_GenerateContextFileWatermark(t *testing.T) {
	dir := t.TempDir()
	a := NewCodexAdapter(dir)

	config := Config{Version: "1", User: UserConfig{Language: "en", Autonomy: "balanced"}}

	if err := a.GenerateContextFile(config, nil, nil, nil); err != nil {
		t.Fatal(err)
	}

	content, _ := os.ReadFile(filepath.Join(dir, "AGENTS.md"))
	if !strings.HasPrefix(string(content), "<!-- Generated by MOM") {
		t.Error("AGENTS.md should start with watermark")
	}
}

func TestCodexAdapter_SupportsHooks(t *testing.T) {
	a := NewCodexAdapter("/tmp/test")
	if !a.SupportsHooks() {
		t.Error("expected SupportsHooks to be true")
	}
}

func TestCodexAdapter_RegisterHooks(t *testing.T) {
	dir := t.TempDir()
	a := NewCodexAdapter(dir)

	if err := a.RegisterHooks(CodexHooks()); err != nil {
		t.Fatalf("RegisterHooks failed: %v", err)
	}

	hooksPath := filepath.Join(dir, ".codex", "hooks.json")
	content, err := os.ReadFile(hooksPath)
	if err != nil {
		t.Fatalf("reading hooks.json: %v", err)
	}

	// The entire file IS the hooks map (no wrapping "hooks" key).
	var hooksMap map[string]any
	if err := json.Unmarshal(content, &hooksMap); err != nil {
		t.Fatalf("parsing hooks.json: %v", err)
	}

	stop, ok := hooksMap["Stop"].([]any)
	if !ok {
		t.Fatal("hooks.json should have a Stop event array")
	}
	if len(stop) != 2 {
		t.Fatalf("expected 2 Stop matcher groups, got %d", len(stop))
	}

	// Verify both "mom record" and "mom draft" are present.
	var commands []string
	for _, entry := range stop {
		group, ok := entry.(map[string]any)
		if !ok {
			t.Fatal("matcher group should be a map")
		}
		innerHooks, ok := group["hooks"].([]any)
		if !ok || len(innerHooks) == 0 {
			t.Fatal("matcher group should have a hooks array")
		}
		hookEntry, ok := innerHooks[0].(map[string]any)
		if !ok {
			t.Fatal("hook entry should be a map")
		}
		if hookEntry["type"] != "command" {
			t.Errorf("expected type 'command', got %v", hookEntry["type"])
		}
		commands = append(commands, hookEntry["command"].(string))
	}

	hasRecord := false
	hasDraft := false
	for _, cmd := range commands {
		if cmd == "mom record" {
			hasRecord = true
		}
		if cmd == "mom draft" {
			hasDraft = true
		}
	}
	if !hasRecord {
		t.Error("hooks.json missing 'mom record' command")
	}
	if !hasDraft {
		t.Error("hooks.json missing 'mom draft' command")
	}
}

func TestCodexAdapter_RegisterMCP(t *testing.T) {
	dir := t.TempDir()
	a := NewCodexAdapter(dir)

	if err := a.RegisterMCP(); err != nil {
		t.Fatalf("RegisterMCP failed: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(dir, ".mcp.json"))
	if err != nil {
		t.Fatalf("reading .mcp.json: %v", err)
	}
	s := string(data)
	if !strings.Contains(s, `"mom"`) {
		t.Error(".mcp.json missing mom server entry")
	}
	if !strings.Contains(s, `"command": "mom"`) {
		t.Error(".mcp.json missing mom command")
	}
	if !strings.Contains(s, `"serve"`) {
		t.Error(".mcp.json missing serve arg")
	}
}

func TestCodexAdapter_GeneratedFiles(t *testing.T) {
	a := NewCodexAdapter("/tmp/test")
	files := a.GeneratedFiles()
	expected := []string{"AGENTS.md", filepath.Join(".codex", "hooks.json"), ".mcp.json"}
	if len(files) != len(expected) {
		t.Fatalf("expected %d files, got %d: %v", len(expected), len(files), files)
	}
	for i, f := range files {
		if f != expected[i] {
			t.Errorf("expected files[%d] = %q, got %q", i, expected[i], f)
		}
	}
}

func TestCodexAdapter_GitIgnorePaths(t *testing.T) {
	a := NewCodexAdapter("/tmp/test")
	paths := a.GitIgnorePaths()
	expected := []string{"AGENTS.md", ".codex/"}
	if len(paths) != len(expected) {
		t.Fatalf("expected %d paths, got %d: %v", len(expected), len(paths), paths)
	}
	for i, p := range paths {
		if p != expected[i] {
			t.Errorf("expected paths[%d] = %q, got %q", i, expected[i], p)
		}
	}
}

func TestCodexAdapter_GeneratedDirs(t *testing.T) {
	a := NewCodexAdapter("/tmp/test")
	dirs := a.GeneratedDirs()
	if len(dirs) != 1 || dirs[0] != ".codex" {
		t.Errorf("expected [.codex], got %v", dirs)
	}
}

func TestCodexAdapter_NoIdentity(t *testing.T) {
	dir := t.TempDir()
	a := NewCodexAdapter(dir)

	config := Config{Version: "1", Delivery: "context-file", User: UserConfig{Language: "en", Autonomy: "balanced"}}

	if err := a.GenerateContextFile(config, nil, nil, nil); err != nil {
		t.Fatal(err)
	}

	content, _ := os.ReadFile(filepath.Join(dir, "AGENTS.md"))
	if !strings.Contains(string(content), "You are MOM") {
		t.Error("should have fallback identity")
	}
}
