package runtime

import (
	"fmt"
	"os"
	"path/filepath"
)

// CodexAdapter implements the Adapter interface for OpenAI Codex.
// It reads from .leo/ and generates AGENTS.md at the project root.
type CodexAdapter struct {
	projectRoot string
}

// NewCodexAdapter creates a CodexAdapter for the given project root.
func NewCodexAdapter(projectRoot string) *CodexAdapter {
	return &CodexAdapter{projectRoot: projectRoot}
}

func (a *CodexAdapter) Name() string {
	return "codex"
}

func (a *CodexAdapter) GenerateContextFile(config Config, constraints []Constraint, skills []Skill, identity *Identity) error {
	content := a.Watermark() + "\n\n" + BuildContextContent(config, constraints, skills, identity)

	agentsFile := filepath.Join(a.projectRoot, "AGENTS.md")
	if err := os.WriteFile(agentsFile, []byte(content), 0644); err != nil {
		return fmt.Errorf("writing AGENTS.md: %w", err)
	}

	return nil
}

func (a *CodexAdapter) SupportsHooks() bool {
	return false
}

func (a *CodexAdapter) RegisterHooks(hooks []HookDef) error {
	return nil
}

func (a *CodexAdapter) DetectRuntime() bool {
	_, err := os.Stat(filepath.Join(a.projectRoot, "AGENTS.md"))
	return err == nil
}

func (a *CodexAdapter) GeneratedFiles() []string {
	return []string{"AGENTS.md"}
}

func (a *CodexAdapter) GeneratedDirs() []string {
	return nil
}

func (a *CodexAdapter) Watermark() string {
	return "<!-- Generated by L.E.O. — do not edit manually -->"
}

func (a *CodexAdapter) DefaultTierMapping() map[string]string {
	return map[string]string{
		"orchestration": "o3",
		"execution":     "gpt-4.1",
		"review":        "gpt-4.1-mini",
	}
}
