package runtime

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestCodexAdapter_Name(t *testing.T) {
	a := NewCodexAdapter("/tmp/test")
	if a.Name() != "codex" {
		t.Errorf("expected %q, got %q", "codex", a.Name())
	}
}

func TestCodexAdapter_DetectRuntime(t *testing.T) {
	dir := t.TempDir()
	a := NewCodexAdapter(dir)

	if a.DetectRuntime() {
		t.Error("expected false when AGENTS.md does not exist")
	}

	os.WriteFile(filepath.Join(dir, "AGENTS.md"), []byte("# agents"), 0644)
	if !a.DetectRuntime() {
		t.Error("expected true when AGENTS.md exists")
	}
}

func TestCodexAdapter_GenerateContextFile(t *testing.T) {
	dir := t.TempDir()
	a := NewCodexAdapter(dir)

	config := Config{
		Version:  "1",
		Delivery: "context-file",
		User:     UserConfig{Language: "en", Autonomy: "balanced", CommunicationMode: "concise"},
	}
	constraints := []Constraint{{ID: "anti-hallucination", Summary: "Don't guess."}}
	skills := []Skill{{ID: "session-wrap-up", Summary: "End-of-session."}}
	identity := &Identity{What: "MOM — a living knowledge infrastructure."}

	if err := a.GenerateContextFile(config, constraints, skills, identity); err != nil {
		t.Fatalf("GenerateContextFile failed: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(dir, "AGENTS.md"))
	if err != nil {
		t.Fatalf("reading AGENTS.md: %v", err)
	}

	s := string(content)
	checks := []string{
		"Generated by MOM",
		"MOM — Memory Oriented Machine",
		"anti-hallucination",
		"session-wrap-up",
		"## Memory",
	}
	for _, check := range checks {
		if !strings.Contains(s, check) {
			t.Errorf("AGENTS.md missing %q", check)
		}
	}
}

func TestCodexAdapter_GenerateContextFileWatermark(t *testing.T) {
	dir := t.TempDir()
	a := NewCodexAdapter(dir)

	config := Config{Version: "1", User: UserConfig{Language: "en", Autonomy: "balanced"}}

	if err := a.GenerateContextFile(config, nil, nil, nil); err != nil {
		t.Fatal(err)
	}

	content, _ := os.ReadFile(filepath.Join(dir, "AGENTS.md"))
	if !strings.HasPrefix(string(content), "<!-- Generated by MOM") {
		t.Error("AGENTS.md should start with watermark")
	}
}

func TestCodexAdapter_GeneratedFiles(t *testing.T) {
	a := NewCodexAdapter("/tmp/test")
	files := a.GeneratedFiles()
	if len(files) != 1 || files[0] != "AGENTS.md" {
		t.Errorf("expected [AGENTS.md], got %v", files)
	}
}

func TestCodexAdapter_GeneratedDirs(t *testing.T) {
	a := NewCodexAdapter("/tmp/test")
	if dirs := a.GeneratedDirs(); dirs != nil {
		t.Errorf("expected nil dirs, got %v", dirs)
	}
}

func TestCodexAdapter_SupportsHooks(t *testing.T) {
	a := NewCodexAdapter("/tmp/test")
	if a.SupportsHooks() {
		t.Error("expected SupportsHooks to be false")
	}
}


func TestCodexAdapter_NoIdentity(t *testing.T) {
	dir := t.TempDir()
	a := NewCodexAdapter(dir)

	config := Config{Version: "1", Delivery: "context-file", User: UserConfig{Language: "en", Autonomy: "balanced"}}

	if err := a.GenerateContextFile(config, nil, nil, nil); err != nil {
		t.Fatal(err)
	}

	content, _ := os.ReadFile(filepath.Join(dir, "AGENTS.md"))
	if !strings.Contains(string(content), "You are MOM") {
		t.Error("should have fallback identity")
	}
}
