package runtime

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

//go:embed capabilities/codex.yaml
var codexCapabilitiesYAML []byte

// CodexAdapter implements the Adapter interface for OpenAI Codex.
// It reads from .mom/ and generates AGENTS.md at the project root.
type CodexAdapter struct {
	projectRoot string
}

// NewCodexAdapter creates a CodexAdapter for the given project root.
func NewCodexAdapter(projectRoot string) *CodexAdapter {
	return &CodexAdapter{projectRoot: projectRoot}
}

func (a *CodexAdapter) Name() string {
	return "codex"
}

func (a *CodexAdapter) GenerateContextFile(config Config, constraints []Constraint, skills []Skill, identity *Identity) error {
	var body string
	if config.Delivery == "context-file" {
		body = BuildContextContent(config, constraints, skills, identity)
	} else {
		body = BuildMinimalContextContent()
	}
	content := a.Watermark() + "\n\n" + body

	agentsFile := filepath.Join(a.projectRoot, "AGENTS.md")
	if err := os.WriteFile(agentsFile, []byte(content), 0644); err != nil {
		return fmt.Errorf("writing AGENTS.md: %w", err)
	}

	return nil
}

func (a *CodexAdapter) SupportsHooks() bool {
	return true
}

func (a *CodexAdapter) RegisterHooks(hooks []HookDef) error {
	codexDir := filepath.Join(a.projectRoot, ".codex")
	hooksPath := filepath.Join(codexDir, "hooks.json")

	// Ensure .codex/ exists.
	if err := os.MkdirAll(codexDir, 0755); err != nil {
		return fmt.Errorf("creating .codex dir: %w", err)
	}

	// Build Codex hooks structure — the entire file IS the hooks map:
	//   { "EventName": [ { "matcher": "...", "hooks": [ {...} ] } ] }
	hooksMap := make(map[string]any)

	// Group HookDefs by event.
	byEvent := make(map[string][]HookDef)
	for _, h := range hooks {
		byEvent[h.Event] = append(byEvent[h.Event], h)
	}

	for event, defs := range byEvent {
		var matcherGroups []map[string]any
		for _, d := range defs {
			entry := map[string]any{
				"type":    "command",
				"command": d.Command,
				"timeout": 10,
			}
			group := map[string]any{
				"hooks": []map[string]any{entry},
			}
			if d.Matcher != "" {
				group["matcher"] = d.Matcher
			}
			matcherGroups = append(matcherGroups, group)
		}
		hooksMap[event] = matcherGroups
	}

	data, err := json.MarshalIndent(hooksMap, "", "  ")
	if err != nil {
		return fmt.Errorf("marshaling hooks: %w", err)
	}

	data = append(data, '\n')
	if err := os.WriteFile(hooksPath, data, 0644); err != nil {
		return fmt.Errorf("writing hooks.json: %w", err)
	}

	return nil
}

// CodexHooks returns the standard MOM hooks for Codex.
// Stop covers both Claude's Stop and SessionEnd — so both record and draft go on Stop.
func CodexHooks() []HookDef {
	return []HookDef{
		{Event: "Stop", Command: "mom record"},
		{Event: "Stop", Command: "mom draft"},
	}
}

// RegisterMCP writes or updates .mcp.json at the project root, injecting the
// MOM MCP server entry. Existing entries for other servers are preserved.
func (a *CodexAdapter) RegisterMCP() error {
	mcpPath := filepath.Join(a.projectRoot, ".mcp.json")

	// Load existing .mcp.json or start fresh.
	root := make(map[string]any)
	if data, err := os.ReadFile(mcpPath); err == nil {
		if err := json.Unmarshal(data, &root); err != nil {
			return fmt.Errorf("parsing .mcp.json: %w", err)
		}
	}

	servers, _ := root["mcpServers"].(map[string]any)
	if servers == nil {
		servers = make(map[string]any)
	}

	servers["mom"] = map[string]any{
		"command": "mom",
		"args":    []string{"serve", "mcp"},
	}
	root["mcpServers"] = servers

	data, err := json.MarshalIndent(root, "", "  ")
	if err != nil {
		return fmt.Errorf("marshaling .mcp.json: %w", err)
	}
	data = append(data, '\n')
	if err := os.WriteFile(mcpPath, data, 0644); err != nil {
		return fmt.Errorf("writing .mcp.json: %w", err)
	}

	return nil
}

func (a *CodexAdapter) DetectRuntime() bool {
	_, err := os.Stat(filepath.Join(a.projectRoot, "AGENTS.md"))
	return err == nil
}

func (a *CodexAdapter) GeneratedFiles() []string {
	return []string{
		"AGENTS.md",
		filepath.Join(".codex", "hooks.json"),
		".mcp.json",
	}
}

func (a *CodexAdapter) GeneratedDirs() []string {
	return []string{".codex"}
}

func (a *CodexAdapter) Watermark() string {
	return "<!-- Generated by MOM — do not edit manually -->"
}

func (a *CodexAdapter) GitIgnorePaths() []string {
	return []string{"AGENTS.md", ".codex/"}
}

func (a *CodexAdapter) Capabilities() AdapterCapability {
	var cap AdapterCapability
	if err := yaml.Unmarshal(codexCapabilitiesYAML, &cap); err != nil {
		return AdapterCapability{Name: "codex", Version: "0.1"}
	}
	return cap
}
