package runtime

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestWindsurfAdapter_GenerateContextFile(t *testing.T) {
	dir := t.TempDir()
	a := NewWindsurfAdapter(dir)

	config := Config{
		Version:  "1",
		Delivery: "context-file",
		User: UserConfig{
			Language:          "en",
			Autonomy:          "balanced",
			CommunicationMode: "concise",
		},
	}

	constraints := []Constraint{
		{ID: "anti-hallucination", Summary: "When unsure, say you don't know."},
	}

	skills := []Skill{
		{ID: "session-wrap-up", Summary: "End-of-session knowledge propagation."},
	}

	identity := &Identity{
		What: "MOM — a living knowledge infrastructure.",
	}

	if err := a.GenerateContextFile(config, constraints, skills, identity); err != nil {
		t.Fatalf("GenerateContextFile failed: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(dir, ".windsurf", "rules", "mom.md"))
	if err != nil {
		t.Fatalf("reading mom.md: %v", err)
	}

	s := string(content)
	if !strings.Contains(s, "Generated by MOM") {
		t.Error("mom.md missing watermark")
	}
	if !strings.Contains(s, "anti-hallucination") {
		t.Error("mom.md missing constraint")
	}
	if !strings.Contains(s, "session-wrap-up") {
		t.Error("mom.md missing skill")
	}
}

func TestWindsurfAdapter_FrontmatterFormat(t *testing.T) {
	dir := t.TempDir()
	a := NewWindsurfAdapter(dir)

	config := Config{
		Version:  "1",
		Delivery: "context-file",
		User:     UserConfig{Language: "en", Autonomy: "balanced", CommunicationMode: "concise"},
	}

	if err := a.GenerateContextFile(config, nil, nil, nil); err != nil {
		t.Fatalf("GenerateContextFile failed: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(dir, ".windsurf", "rules", "mom.md"))
	if err != nil {
		t.Fatalf("reading mom.md: %v", err)
	}

	s := string(content)
	if !strings.HasPrefix(s, "---\ntrigger: always_on\n---") {
		t.Errorf("mom.md should start with YAML frontmatter, got: %q", s[:min(len(s), 60)])
	}
}

func TestWindsurfAdapter_RegisterHooks(t *testing.T) {
	dir := t.TempDir()
	a := NewWindsurfAdapter(dir)

	if err := a.RegisterHooks(WindsurfHooks()); err != nil {
		t.Fatalf("RegisterHooks failed: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(dir, ".windsurf", "hooks.json"))
	if err != nil {
		t.Fatalf("reading hooks.json: %v", err)
	}

	var hooksMap map[string]any
	if err := json.Unmarshal(content, &hooksMap); err != nil {
		t.Fatalf("parsing hooks.json: %v", err)
	}

	// Windsurf hooks use post_cascade_response_with_transcript event.
	event, ok := hooksMap["post_cascade_response_with_transcript"].([]any)
	if !ok {
		t.Fatal("hooks.json missing post_cascade_response_with_transcript event")
	}
	if len(event) != 2 {
		t.Fatalf("expected 2 matcher groups, got %d", len(event))
	}

	// Verify first hook command is "mom record".
	group0 := event[0].(map[string]any)
	innerHooks0 := group0["hooks"].([]any)
	entry0 := innerHooks0[0].(map[string]any)
	if entry0["command"] != "mom record" {
		t.Errorf("expected command 'mom record', got %v", entry0["command"])
	}

	// Verify second hook command is "mom draft".
	group1 := event[1].(map[string]any)
	innerHooks1 := group1["hooks"].([]any)
	entry1 := innerHooks1[0].(map[string]any)
	if entry1["command"] != "mom draft" {
		t.Errorf("expected command 'mom draft', got %v", entry1["command"])
	}

	// Verify top-level format (no nested "hooks" key wrapping the event map).
	if _, hasNestedHooks := hooksMap["hooks"]; hasNestedHooks {
		t.Error("hooks.json should NOT have a nested 'hooks' key — events should be top-level")
	}
}

func TestWindsurfAdapter_RegisterMCP(t *testing.T) {
	dir := t.TempDir()
	a := NewWindsurfAdapter(dir)

	if err := a.RegisterMCP(); err != nil {
		t.Fatalf("RegisterMCP failed: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(dir, ".mcp.json"))
	if err != nil {
		t.Fatalf("reading .mcp.json: %v", err)
	}
	s := string(data)
	if !strings.Contains(s, `"mom"`) {
		t.Error(".mcp.json missing mom server entry")
	}
	if !strings.Contains(s, `"command": "mom"`) {
		t.Error(".mcp.json missing mom command")
	}
	if !strings.Contains(s, `"serve"`) {
		t.Error(".mcp.json missing serve arg")
	}
}

func TestWindsurfAdapter_GeneratedFiles(t *testing.T) {
	a := NewWindsurfAdapter("/tmp/test")
	files := a.GeneratedFiles()

	expected := []string{
		filepath.Join(".windsurf", "rules", "mom.md"),
		filepath.Join(".windsurf", "hooks.json"),
		".mcp.json",
	}

	if len(files) != len(expected) {
		t.Fatalf("expected %d files, got %d", len(expected), len(files))
	}

	for i, f := range files {
		if f != expected[i] {
			t.Errorf("file[%d]: expected %q, got %q", i, expected[i], f)
		}
	}
}

func TestWindsurfAdapter_GitIgnorePaths(t *testing.T) {
	a := NewWindsurfAdapter("/tmp/test")
	paths := a.GitIgnorePaths()

	if len(paths) != 1 || paths[0] != ".windsurf/" {
		t.Errorf("expected [.windsurf/], got %v", paths)
	}
}

func TestWindsurfAdapter_DetectRuntime(t *testing.T) {
	dir := t.TempDir()
	a := NewWindsurfAdapter(dir)

	if a.DetectRuntime() {
		t.Error("expected false when .windsurf/ does not exist")
	}

	os.MkdirAll(filepath.Join(dir, ".windsurf"), 0755)
	if !a.DetectRuntime() {
		t.Error("expected true when .windsurf/ exists")
	}
}
