package runtime

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

//go:embed capabilities/windsurf.yaml
var windsurfCapabilitiesYAML []byte

// WindsurfAdapter implements the Adapter interface for Windsurf.
// It reads from .mom/ and generates .windsurf/rules/mom.md + hooks.json.
type WindsurfAdapter struct {
	projectRoot string
}

// NewWindsurfAdapter creates a WindsurfAdapter for the given project root.
func NewWindsurfAdapter(projectRoot string) *WindsurfAdapter {
	return &WindsurfAdapter{projectRoot: projectRoot}
}

func (a *WindsurfAdapter) Name() string {
	return "windsurf"
}

func (a *WindsurfAdapter) GenerateContextFile(config Config, constraints []Constraint, skills []Skill, identity *Identity) error {
	rulesDir := filepath.Join(a.projectRoot, ".windsurf", "rules")
	if err := os.MkdirAll(rulesDir, 0755); err != nil {
		return fmt.Errorf("creating .windsurf/rules dir: %w", err)
	}

	var body string
	if config.Delivery == "context-file" {
		body = BuildContextContent(config, constraints, skills, identity)
	} else {
		body = BuildMinimalContextContent()
	}

	// Windsurf rules require YAML frontmatter
	frontmatter := "---\ntrigger: always_on\n---\n\n"
	content := frontmatter + a.Watermark() + "\n\n" + body

	contextFile := filepath.Join(rulesDir, "mom.md")
	if err := os.WriteFile(contextFile, []byte(content), 0644); err != nil {
		return fmt.Errorf("writing mom.md: %w", err)
	}
	return nil
}

func (a *WindsurfAdapter) SupportsHooks() bool {
	return true
}

func (a *WindsurfAdapter) RegisterHooks(hooks []HookDef) error {
	windsurfDir := filepath.Join(a.projectRoot, ".windsurf")
	if err := os.MkdirAll(windsurfDir, 0755); err != nil {
		return fmt.Errorf("creating .windsurf dir: %w", err)
	}

	hooksPath := filepath.Join(windsurfDir, "hooks.json")

	hooksMap := make(map[string]any)
	byEvent := make(map[string][]HookDef)
	for _, h := range hooks {
		byEvent[h.Event] = append(byEvent[h.Event], h)
	}

	for event, defs := range byEvent {
		var matcherGroups []map[string]any
		for _, d := range defs {
			entry := map[string]any{
				"type":    "command",
				"command": d.Command,
				"timeout": 10,
			}
			group := map[string]any{
				"hooks": []map[string]any{entry},
			}
			if d.Matcher != "" {
				group["matcher"] = d.Matcher
			}
			matcherGroups = append(matcherGroups, group)
		}
		hooksMap[event] = matcherGroups
	}

	data, err := json.MarshalIndent(hooksMap, "", "  ")
	if err != nil {
		return fmt.Errorf("marshaling hooks: %w", err)
	}
	data = append(data, '\n')
	if err := os.WriteFile(hooksPath, data, 0644); err != nil {
		return fmt.Errorf("writing hooks.json: %w", err)
	}
	return nil
}

// WindsurfHooks returns the standard MOM hooks for Windsurf.
// post_cascade_response_with_transcript → mom record: captures raw transcript after each response.
// post_cascade_response_with_transcript → mom draft: processes raw into draft memories.
func WindsurfHooks() []HookDef {
	return []HookDef{
		{Event: "post_cascade_response_with_transcript", Command: "mom record"},
		{Event: "post_cascade_response_with_transcript", Command: "mom draft"},
	}
}

func (a *WindsurfAdapter) DetectRuntime() bool {
	info, err := os.Stat(filepath.Join(a.projectRoot, ".windsurf"))
	return err == nil && info.IsDir()
}

// RegisterMCP writes or updates .mcp.json at the project root, injecting the
// MOM MCP server entry. Existing entries for other servers are preserved.
func (a *WindsurfAdapter) RegisterMCP() error {
	mcpPath := filepath.Join(a.projectRoot, ".mcp.json")

	// Load existing .mcp.json or start fresh.
	root := make(map[string]any)
	if data, err := os.ReadFile(mcpPath); err == nil {
		if err := json.Unmarshal(data, &root); err != nil {
			return fmt.Errorf("parsing .mcp.json: %w", err)
		}
	}

	servers, _ := root["mcpServers"].(map[string]any)
	if servers == nil {
		servers = make(map[string]any)
	}

	servers["mom"] = map[string]any{
		"command": "mom",
		"args":    []string{"serve", "mcp"},
	}
	root["mcpServers"] = servers

	data, err := json.MarshalIndent(root, "", "  ")
	if err != nil {
		return fmt.Errorf("marshaling .mcp.json: %w", err)
	}
	data = append(data, '\n')
	if err := os.WriteFile(mcpPath, data, 0644); err != nil {
		return fmt.Errorf("writing .mcp.json: %w", err)
	}

	return nil
}

func (a *WindsurfAdapter) GeneratedFiles() []string {
	return []string{
		filepath.Join(".windsurf", "rules", "mom.md"),
		filepath.Join(".windsurf", "hooks.json"),
		".mcp.json",
	}
}

func (a *WindsurfAdapter) GeneratedDirs() []string {
	return []string{".windsurf"}
}

func (a *WindsurfAdapter) Watermark() string {
	return "<!-- Generated by MOM — do not edit manually -->"
}

func (a *WindsurfAdapter) GitIgnorePaths() []string {
	return []string{".windsurf/"}
}

func (a *WindsurfAdapter) Capabilities() AdapterCapability {
	var cap AdapterCapability
	if err := yaml.Unmarshal(windsurfCapabilitiesYAML, &cap); err != nil {
		// Fallback: return minimal capability if YAML is malformed.
		return AdapterCapability{Name: "windsurf", Version: "1.0"}
	}
	return cap
}
