package cmd

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/momhq/mom/cli/internal/config"
	"github.com/momhq/mom/cli/internal/recorder"
)

// ── Helpers ──────────────────────────────────────────────────────────────────

func resetInitFlags() {
	f := initCmd.Flags()
	// StringSlice.Set appends when changed=true, so clear Changed first.
	if rt := f.Lookup("runtimes"); rt != nil {
		rt.Changed = false
		rt.Value.Set("")
		rt.Changed = false
	}
	f.Set("force", "false")
	f.Set("no-interactive", "false")
}

func initProject(t *testing.T, dir string, runtimes []string) string {
	t.Helper()
	origDir, _ := os.Getwd()
	os.Chdir(dir)
	t.Cleanup(func() { os.Chdir(origDir) })

	// Reset flags BEFORE execute to avoid cross-test contamination.
	resetInitFlags()

	buf := new(bytes.Buffer)
	rootCmd.SetOut(buf)
	rootCmd.SetErr(buf)
	rootCmd.SetArgs([]string{"init", "--runtimes", strings.Join(runtimes, ",")})
	t.Cleanup(resetInitFlags)

	if err := rootCmd.Execute(); err != nil {
		t.Fatalf("init failed: %v\noutput: %s", err, buf.String())
	}
	return buf.String()
}

func upgradeProject(t *testing.T, dir string, extraArgs ...string) string {
	t.Helper()
	origDir, _ := os.Getwd()
	os.Chdir(dir)
	t.Cleanup(func() { os.Chdir(origDir) })

	buf := new(bytes.Buffer)
	rootCmd.SetOut(buf)
	rootCmd.SetErr(buf)
	args := append([]string{"upgrade"}, extraArgs...)
	rootCmd.SetArgs(args)
	t.Cleanup(func() {
		upgradeCmd.Flags().Set("dry-run", "false")
		upgradeCmd.Flags().Set("all", "false")
	})

	if err := rootCmd.Execute(); err != nil {
		t.Fatalf("upgrade failed: %v\noutput: %s", err, buf.String())
	}
	return buf.String()
}

func assertFileExists(t *testing.T, path string) {
	t.Helper()
	if _, err := os.Stat(path); err != nil {
		t.Errorf("expected file to exist: %s", path)
	}
}

func assertFileNotExists(t *testing.T, path string) {
	t.Helper()
	if _, err := os.Stat(path); err == nil {
		t.Errorf("expected file NOT to exist: %s", path)
	}
}

func assertFileContains(t *testing.T, path, substr string) {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Errorf("cannot read %s: %v", path, err)
		return
	}
	if !strings.Contains(string(data), substr) {
		t.Errorf("%s does not contain %q", path, substr)
	}
}

func readJSONFile(t *testing.T, path string) map[string]any {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("cannot read %s: %v", path, err)
	}
	var m map[string]any
	if err := json.Unmarshal(data, &m); err != nil {
		t.Fatalf("cannot parse %s: %v", path, err)
	}
	return m
}

func assertMCPEntry(t *testing.T, mcpPath string) {
	t.Helper()
	m := readJSONFile(t, mcpPath)
	servers, ok := m["mcpServers"].(map[string]any)
	if !ok {
		t.Fatalf("%s missing mcpServers key", mcpPath)
	}
	mom, ok := servers["mom"].(map[string]any)
	if !ok {
		t.Fatalf("%s missing mcpServers.mom", mcpPath)
	}
	cmd, _ := mom["command"].(string)
	if cmd == "" {
		t.Errorf("%s mcpServers.mom.command must not be empty, got %v", mcpPath, mom["command"])
	}
}

func setupMinimalMom(t *testing.T, dir string, runtimes []string) {
	t.Helper()
	momDir := filepath.Join(dir, ".mom")
	for _, d := range []string{"memory", "constraints", "skills", "logs", "cache", "raw"} {
		os.MkdirAll(filepath.Join(momDir, d), 0755)
	}

	cfg := config.Default()
	cfg.Harnesses = make(map[string]config.HarnessConfig)
	for _, rt := range runtimes {
		cfg.Harnesses[rt] = config.HarnessConfig{Enabled: true}
	}
	cfg.Communication.Mode = "efficient"
	if err := config.Save(momDir, &cfg); err != nil {
		t.Fatalf("saving config: %v", err)
	}

	// Write minimal identity and schema so upgrade doesn't fail.
	os.WriteFile(filepath.Join(momDir, "identity.json"), []byte(`{"old": true}`), 0644)
	os.WriteFile(filepath.Join(momDir, "schema.json"), []byte(`{"old": true}`), 0644)
}

// ── Test 1: Init with all runtimes ──────────────────────────────────────────

func TestIntegration_InitAllRuntimes(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("HOME", dir) // isolate global configs

	allRuntimes := []string{"claude", "codex", "windsurf", "pi"}
	initProject(t, dir, allRuntimes)

	// ── .mom/ structure ──
	assertFileExists(t, filepath.Join(dir, ".mom", "config.yaml"))
	assertFileExists(t, filepath.Join(dir, ".mom", "identity.json"))
	assertFileExists(t, filepath.Join(dir, ".mom", "schema.json"))

	cfg, err := config.Load(filepath.Join(dir, ".mom"))
	if err != nil {
		t.Fatalf("loading config: %v", err)
	}
	enabled := cfg.EnabledRuntimes()
	if len(enabled) != 4 {
		t.Errorf("expected 4 enabled runtimes, got %d: %v", len(enabled), enabled)
	}

	// ── Claude ──
	claudeMD := filepath.Join(dir, ".claude", "CLAUDE.md")
	assertFileExists(t, claudeMD)
	assertFileContains(t, claudeMD, "Generated by MOM")

	settingsJSON := filepath.Join(dir, ".claude", "settings.json")
	assertFileExists(t, settingsJSON)
	assertFileContains(t, settingsJSON, "mom draft")
	// mom record hook removed — recording now via mom watch (#137)

	// ── Codex ──
	agentsMD := filepath.Join(dir, "AGENTS.md")
	assertFileExists(t, agentsMD)
	assertFileContains(t, agentsMD, "Generated by MOM")

	codexHooks := filepath.Join(dir, ".codex", "hooks.json")
	assertFileExists(t, codexHooks)
	assertFileContains(t, codexHooks, "mom record")

	// ── Windsurf ──
	windsurfMD := filepath.Join(dir, ".windsurf", "rules", "mom.md")
	assertFileExists(t, windsurfMD)
	assertFileContains(t, windsurfMD, "trigger: always_on")
	assertFileContains(t, windsurfMD, "Generated by MOM")

	windsurfHooks := filepath.Join(dir, ".windsurf", "hooks.json")
	assertFileExists(t, windsurfHooks)
	assertFileContains(t, windsurfHooks, "mom draft")
	// mom record hook removed — recording now via mom watch (#145)
	assertFileContains(t, windsurfHooks, "working_directory")

	// ── Pi ──
	// Pi shares AGENTS.md with Codex (already asserted above) and lays down
	// its MCP-tool-bridging extension under .pi/extensions/.
	piExt := filepath.Join(dir, ".pi", "extensions", "mom-tools.ts")
	assertFileExists(t, piExt)
	assertFileContains(t, piExt, "export default")
	assertFileContains(t, piExt, "pi.registerTool")

	// ── MCP config ──
	mcpJSON := filepath.Join(dir, ".mcp.json")
	assertMCPEntry(t, mcpJSON)

	// Windsurf should add MOM_PROJECT_DIR to .mcp.json
	assertFileContains(t, mcpJSON, "MOM_PROJECT_DIR")
}

// ── Test 2: Upgrade registers ALL runtimes (regression) ─────────────────────

func TestIntegration_UpgradeRegistersAllRuntimes(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("HOME", dir)

	allRuntimes := []string{"claude", "codex", "windsurf", "pi"}
	setupMinimalMom(t, dir, allRuntimes)

	// No runtime artifacts exist yet — this simulates the bug scenario.
	assertFileNotExists(t, filepath.Join(dir, ".claude", "CLAUDE.md"))
	assertFileNotExists(t, filepath.Join(dir, "AGENTS.md"))
	assertFileNotExists(t, filepath.Join(dir, ".windsurf", "rules", "mom.md"))
	assertFileNotExists(t, filepath.Join(dir, ".pi", "extensions", "mom-tools.ts"))

	output := upgradeProject(t, dir)

	// ALL runtimes must be regenerated — not just Claude.
	for _, rt := range allRuntimes {
		if !strings.Contains(output, "runtime "+rt+" context file regenerated") {
			t.Errorf("upgrade output missing regeneration for runtime %s", rt)
		}
	}

	// ── Verify artifacts created for ALL runtimes ──
	assertFileExists(t, filepath.Join(dir, ".claude", "CLAUDE.md"))
	assertFileContains(t, filepath.Join(dir, ".claude", "CLAUDE.md"), "Generated by MOM")

	assertFileExists(t, filepath.Join(dir, ".claude", "settings.json"))
	assertFileContains(t, filepath.Join(dir, ".claude", "settings.json"), "mom draft")

	assertFileExists(t, filepath.Join(dir, "AGENTS.md"))
	assertFileExists(t, filepath.Join(dir, ".codex", "hooks.json"))
	assertFileContains(t, filepath.Join(dir, ".codex", "hooks.json"), "mom record")

	assertFileExists(t, filepath.Join(dir, ".windsurf", "rules", "mom.md"))
	assertFileExists(t, filepath.Join(dir, ".windsurf", "hooks.json"))
	assertFileContains(t, filepath.Join(dir, ".windsurf", "hooks.json"), "working_directory")

	// Pi: extension must be deployed by upgrade too.
	assertFileExists(t, filepath.Join(dir, ".pi", "extensions", "mom-tools.ts"))
	assertFileContains(t, filepath.Join(dir, ".pi", "extensions", "mom-tools.ts"), "pi.registerTool")

	// MCP config must exist with mom entry.
	assertMCPEntry(t, filepath.Join(dir, ".mcp.json"))
}

// ── Test 3: Upgrade --all propagation ───────────────────────────────────────

func TestIntegration_UpgradeAllPropagation(t *testing.T) {
	root := t.TempDir()
	t.Setenv("HOME", root)

	// Build hierarchy: root (user) → org-a (org) → repo-1, repo-2 (repos)
	orgDir := filepath.Join(root, "org-a")
	repo1 := filepath.Join(orgDir, "repo-1")
	repo2 := filepath.Join(orgDir, "repo-2")

	for _, d := range []string{repo1, repo2} {
		os.MkdirAll(filepath.Join(d, ".git"), 0755)
	}

	// Init .mom/ at each level with claude only.
	for _, pair := range []struct {
		dir   string
		scope string
	}{
		{root, "user"},
		{orgDir, "org"},
		{repo1, "repo"},
		{repo2, "repo"},
	} {
		momDir := filepath.Join(pair.dir, ".mom")
		os.MkdirAll(filepath.Join(momDir, "memory"), 0755)
		cfg := config.Default()
		cfg.Scope = pair.scope
		config.Save(momDir, &cfg)
		os.WriteFile(filepath.Join(momDir, "identity.json"), []byte(`{"old": true}`), 0644)
		os.WriteFile(filepath.Join(momDir, "schema.json"), []byte(`{"old": true}`), 0644)
	}

	upgradeProject(t, root, "--all")

	// All levels should have updated schema.json (not the old placeholder).
	for _, d := range []string{root, orgDir, repo1, repo2} {
		schemaPath := filepath.Join(d, ".mom", "schema.json")
		data, err := os.ReadFile(schemaPath)
		if err != nil {
			t.Errorf("missing schema.json in %s", d)
			continue
		}
		if string(data) == `{"old": true}` {
			t.Errorf("schema.json not updated in %s", d)
		}
	}

	// All levels should have Claude context file.
	for _, d := range []string{root, orgDir, repo1, repo2} {
		assertFileExists(t, filepath.Join(d, ".claude", "CLAUDE.md"))
	}
}

// ── Test 4: Add runtimes via upgrade ────────────────────────────────────────

func TestIntegration_AddRuntimesViaUpgrade(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("HOME", dir)

	// Set up a minimal .mom/ with claude only (avoids cobra flag leakage).
	setupMinimalMom(t, dir, []string{"claude"})

	// Claude artifacts do NOT exist yet (setupMinimalMom only creates config).
	assertFileNotExists(t, filepath.Join(dir, ".windsurf", "rules", "mom.md"))
	assertFileNotExists(t, filepath.Join(dir, "AGENTS.md"))

	// Run upgrade to generate claude artifacts.
	upgradeProject(t, dir)

	// Claude artifacts should exist now.
	assertFileExists(t, filepath.Join(dir, ".claude", "CLAUDE.md"))
	// Windsurf and Codex should NOT exist (only claude is in config).
	assertFileNotExists(t, filepath.Join(dir, ".windsurf", "rules", "mom.md"))
	assertFileNotExists(t, filepath.Join(dir, "AGENTS.md"))

	// Add windsurf + codex to config.
	momDir := filepath.Join(dir, ".mom")
	cfg, _ := config.Load(momDir)
	cfg.Harnesses["windsurf"] = config.HarnessConfig{Enabled: true}
	cfg.Harnesses["codex"] = config.HarnessConfig{Enabled: true}
	config.Save(momDir, cfg)

	// Upgrade should pick up new runtimes.
	upgradeProject(t, dir)

	// All three should now exist.
	assertFileExists(t, filepath.Join(dir, ".claude", "CLAUDE.md"))
	assertFileExists(t, filepath.Join(dir, ".windsurf", "rules", "mom.md"))
	assertFileExists(t, filepath.Join(dir, ".windsurf", "hooks.json"))
	assertFileExists(t, filepath.Join(dir, "AGENTS.md"))
	assertFileExists(t, filepath.Join(dir, ".codex", "hooks.json"))
	assertMCPEntry(t, filepath.Join(dir, ".mcp.json"))
}

// ── Test 5: Record + Draft pipeline ─────────────────────────────────────────

func TestIntegration_RecordDraftPipeline(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("HOME", dir)

	initProject(t, dir, []string{"claude"})

	momDir := filepath.Join(dir, ".mom")
	rawDir := filepath.Join(momDir, "raw")
	memDir := filepath.Join(momDir, "memory")

	// Use RecordText to write raw entries directly (avoids transcript file complexity).
	recorder.RecordText(momDir, "User: How does the auth middleware work?\nAssistant: The auth middleware validates JWT tokens from the Authorization header.", "test-session")
	recorder.RecordText(momDir, "User: What about refresh tokens?\nAssistant: Refresh tokens are stored in HTTP-only cookies and rotated on each use.", "test-session")

	// Verify raw JSONL was created.
	rawEntries, err := os.ReadDir(rawDir)
	if err != nil {
		t.Fatalf("reading raw dir: %v", err)
	}
	var jsonlCount int
	for _, e := range rawEntries {
		if filepath.Ext(e.Name()) == ".jsonl" {
			jsonlCount++
		}
	}
	if jsonlCount == 0 {
		t.Fatal("no .jsonl files created in .mom/raw/")
	}

	// Set draft cursor to the past so drafter picks up our entries.
	cursorFile := filepath.Join(rawDir, ".draft-cursor")
	os.WriteFile(cursorFile, []byte("2020-01-01T00:00:00Z"), 0644)

	// Run draft command.
	buf := new(bytes.Buffer)
	rootCmd.SetOut(buf)
	rootCmd.SetErr(buf)
	rootCmd.SetArgs([]string{"draft"})
	// Draft reads from stdin for hook input; provide empty input.
	oldStdin := os.Stdin
	r, w, _ := os.Pipe()
	w.Close()
	os.Stdin = r
	defer func() { os.Stdin = oldStdin }()

	if err := rootCmd.Execute(); err != nil {
		t.Fatalf("draft failed: %v\noutput: %s", err, buf.String())
	}

	// Verify memory drafts were created (drafter output stays as draft).
	memEntries, err := os.ReadDir(memDir)
	if err != nil {
		t.Fatalf("reading memory dir: %v", err)
	}
	var draftCount int
	for _, e := range memEntries {
		if filepath.Ext(e.Name()) == ".json" {
			data, _ := os.ReadFile(filepath.Join(memDir, e.Name()))
			if strings.Contains(string(data), `"promotion_state":"draft"`) ||
				strings.Contains(string(data), `"promotion_state": "draft"`) {
				draftCount++
			}
		}
	}
	if draftCount == 0 {
		t.Error("no draft memory docs created in .mom/memory/")
	}
}

// ── Test 6: MCP config correctness ──────────────────────────────────────────

func TestIntegration_MCPConfigCorrectness(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("HOME", dir)

	allRuntimes := []string{"claude", "codex", "windsurf"}
	initProject(t, dir, allRuntimes)

	mcpPath := filepath.Join(dir, ".mcp.json")

	// Verify structure.
	m := readJSONFile(t, mcpPath)
	servers, ok := m["mcpServers"].(map[string]any)
	if !ok {
		t.Fatal(".mcp.json missing mcpServers")
	}

	mom, ok := servers["mom"].(map[string]any)
	if !ok {
		t.Fatal(".mcp.json missing mcpServers.mom")
	}

	cmd, _ := mom["command"].(string)
	if cmd == "" {
		t.Errorf("mcpServers.mom.command must not be empty, got %v", mom["command"])
	}

	args, ok := mom["args"].([]any)
	if !ok || len(args) < 2 {
		t.Errorf("mcpServers.mom.args missing or too short: %v", mom["args"])
	}

	// Windsurf adds MOM_PROJECT_DIR env.
	env, _ := mom["env"].(map[string]any)
	if env == nil {
		t.Error("mcpServers.mom.env is nil — expected MOM_PROJECT_DIR")
	} else if _, ok := env["MOM_PROJECT_DIR"]; !ok {
		t.Error("mcpServers.mom.env missing MOM_PROJECT_DIR")
	}
}

// ── Test 7: Upgrade preserves custom MCP entries ────────────────────────────

func TestIntegration_UpgradePreservesCustomMCP(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("HOME", dir)

	initProject(t, dir, []string{"claude", "windsurf"})

	mcpPath := filepath.Join(dir, ".mcp.json")

	// Add a custom MCP server entry alongside mom.
	m := readJSONFile(t, mcpPath)
	servers := m["mcpServers"].(map[string]any)
	servers["my-custom-server"] = map[string]any{
		"command": "my-server",
		"args":    []string{"start"},
	}
	m["mcpServers"] = servers

	data, _ := json.MarshalIndent(m, "", "  ")
	data = append(data, '\n')
	os.WriteFile(mcpPath, data, 0644)

	// Verify custom entry exists before upgrade.
	pre := readJSONFile(t, mcpPath)
	preSrv := pre["mcpServers"].(map[string]any)
	if _, ok := preSrv["my-custom-server"]; !ok {
		t.Fatal("custom server not written to .mcp.json")
	}

	// Run upgrade.
	upgradeProject(t, dir)

	// Verify both mom and custom server survive.
	post := readJSONFile(t, mcpPath)
	postSrv := post["mcpServers"].(map[string]any)

	if _, ok := postSrv["mom"]; !ok {
		t.Error("mcpServers.mom missing after upgrade")
	}
	if _, ok := postSrv["my-custom-server"]; !ok {
		t.Error("mcpServers.my-custom-server lost after upgrade — custom entries not preserved")
	}

	// Verify custom server content is intact.
	custom := postSrv["my-custom-server"].(map[string]any)
	if custom["command"] != "my-server" {
		t.Errorf("custom server command = %v, want my-server", custom["command"])
	}
}