package cmd

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"github.com/vmarinogg/leo-core/cli/internal/adapters/runtime"
	"github.com/vmarinogg/leo-core/cli/internal/config"
)

var uninstallCmd = &cobra.Command{
	Use:   "uninstall",
	Short: "Remove all Leo files from this project",
	Long: `Removes .leo/ directory and any generated runtime files (e.g. .claude/CLAUDE.md).
Optionally backs up your KB before removal using the export command.`,
	RunE: runUninstall,
}

func init() {
	uninstallCmd.Flags().BoolP("yes", "y", false, "Skip confirmation prompt")
	uninstallCmd.Flags().Bool("no-backup", false, "Skip backup prompt — delete without exporting")
	uninstallCmd.Flags().Bool("force", false, "Force removal even if .leo/ is not found")
}

// adapterForRuntime returns the appropriate adapter for the given runtime name.
func adapterForRuntime(rt string, projectRoot string) runtime.Adapter {
	switch rt {
	case "claude":
		return runtime.NewClaudeAdapter(projectRoot)
	// Future: case "cursor": return runtime.NewCursorAdapter(projectRoot)
	default:
		return runtime.NewClaudeAdapter(projectRoot)
	}
}

func runUninstall(cmd *cobra.Command, args []string) error {
	cwd, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("getting cwd: %w", err)
	}

	leoDir := filepath.Join(cwd, ".leo")
	hasLeoDir := true
	if _, err := os.Stat(leoDir); err != nil {
		force, _ := cmd.Flags().GetBool("force")
		if !force {
			return fmt.Errorf("no .leo/ directory found in %s", cwd)
		}
		hasLeoDir = false
	}

	// Resolve the adapter from config (or default to claude).
	var adapter runtime.Adapter
	if hasLeoDir {
		cfg, err := config.Load(leoDir)
		if err == nil {
			adapter = adapterForRuntime(cfg.Runtime, cwd)
		} else {
			adapter = runtime.NewClaudeAdapter(cwd)
		}
	} else {
		adapter = runtime.NewClaudeAdapter(cwd)
	}

	yes, _ := cmd.Flags().GetBool("yes")
	noBackup, _ := cmd.Flags().GetBool("no-backup")

	// Confirm with user.
	if !yes {
		cmd.Println("This will remove all Leo files from this project:")
		if hasLeoDir {
			cmd.Println("  - .leo/ (config, KB, profiles, cache)")
		}
		for _, f := range adapter.GeneratedFiles() {
			cmd.Printf("  - %s (if generated by Leo)\n", f)
		}
		cmd.Println()
		cmd.Print("  Proceed? [y/N]: ")

		scanner := bufio.NewScanner(cmd.InOrStdin())
		answer := ""
		if scanner.Scan() {
			answer = strings.TrimSpace(scanner.Text())
		}
		if strings.ToLower(answer) != "y" {
			return fmt.Errorf("uninstall aborted")
		}
	}

	// Offer backup.
	if hasLeoDir && !noBackup {
		doBackup := false
		if yes {
			doBackup = true
		} else {
			cmd.Print("  Back up KB before removing? [Y/n]: ")
			scanner := bufio.NewScanner(cmd.InOrStdin())
			answer := ""
			if scanner.Scan() {
				answer = strings.TrimSpace(scanner.Text())
			}
			doBackup = answer == "" || strings.ToLower(answer) == "y"
		}

		if doBackup {
			exportDir := filepath.Join(cwd, "leo-export")
			cmd.Printf("  Exporting to %s...\n", exportDir)
			exportCmd.Flags().Set("output", exportDir) //nolint:errcheck
			if err := runExport(cmd, nil); err != nil {
				return fmt.Errorf("backup failed: %w — aborting uninstall", err)
			}
			cmd.Println("  ✔ Backup complete")
		}
	}

	// Remove .leo/.
	if hasLeoDir {
		if err := os.RemoveAll(leoDir); err != nil {
			return fmt.Errorf("removing .leo/: %w", err)
		}
		cmd.Println("  ✔ Removed .leo/")
	}

	// Remove generated runtime files via adapter.
	for _, relPath := range adapter.GeneratedFiles() {
		absPath := filepath.Join(cwd, relPath)
		if _, err := os.Stat(absPath); err == nil {
			os.Remove(absPath)
			cmd.Printf("  ✔ Removed %s\n", relPath)
		}
	}

	// Remove generated dirs if empty.
	for _, relDir := range adapter.GeneratedDirs() {
		absDir := filepath.Join(cwd, relDir)
		entries, err := os.ReadDir(absDir)
		if err == nil && len(entries) == 0 {
			os.Remove(absDir)
			cmd.Printf("  ✔ Removed empty %s/\n", relDir)
		}
	}

	cmd.Println("\n  Leo has been removed from this project.")
	return nil
}
