package cli

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/momhq/mom/shared/config"
)

// ── Helpers ──────────────────────────────────────────────────────────────────

func resetInitFlags() {
	f := initCmd.Flags()
	if h := f.Lookup("harnesses"); h != nil {
		h.Value.Set("")
		h.Changed = false
	}
	f.Set("force", "false")
	f.Set("no-interactive", "false")
}

func initProject(t *testing.T, dir string, harnesses []string) string {
	t.Helper()
	origDir, _ := os.Getwd()
	os.Chdir(dir)
	t.Cleanup(func() { os.Chdir(origDir) })

	// Reset flags BEFORE execute to avoid cross-test contamination.
	resetInitFlags()
	oldRunner := runExternalCommand
	runExternalCommand = func(string, ...string) ([]byte, error) { return []byte("ok"), nil }
	t.Cleanup(func() { runExternalCommand = oldRunner })

	buf := new(bytes.Buffer)
	rootCmd.SetOut(buf)
	rootCmd.SetErr(buf)
	rootCmd.SetArgs([]string{"init", "--harnesses", strings.Join(harnesses, ",")})
	t.Cleanup(resetInitFlags)

	if err := rootCmd.Execute(); err != nil {
		t.Fatalf("init failed: %v\noutput: %s", err, buf.String())
	}
	return buf.String()
}

func upgradeProject(t *testing.T, dir string, extraArgs ...string) string {
	t.Helper()
	origDir, _ := os.Getwd()
	os.Chdir(dir)
	t.Cleanup(func() { os.Chdir(origDir) })

	buf := new(bytes.Buffer)
	rootCmd.SetOut(buf)
	rootCmd.SetErr(buf)
	args := append([]string{"upgrade"}, extraArgs...)
	rootCmd.SetArgs(args)
	t.Cleanup(func() {
		upgradeCmd.Flags().Set("dry-run", "false")
	})

	if err := rootCmd.Execute(); err != nil {
		t.Fatalf("upgrade failed: %v\noutput: %s", err, buf.String())
	}
	return buf.String()
}

func assertFileExists(t *testing.T, path string) {
	t.Helper()
	if _, err := os.Stat(path); err != nil {
		t.Errorf("expected file to exist: %s", path)
	}
}

func assertFileNotExists(t *testing.T, path string) {
	t.Helper()
	if _, err := os.Stat(path); err == nil {
		t.Errorf("expected file NOT to exist: %s", path)
	}
}

func assertFileContains(t *testing.T, path, substr string) {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Errorf("cannot read %s: %v", path, err)
		return
	}
	if !strings.Contains(string(data), substr) {
		t.Errorf("%s does not contain %q", path, substr)
	}
}

func setupMinimalMom(t *testing.T, dir string, harnesses []string) {
	t.Helper()
	momDir := filepath.Join(dir, ".mom")
	for _, d := range []string{"memory", "constraints", "skills", "logs", "cache", "raw"} {
		os.MkdirAll(filepath.Join(momDir, d), 0755)
	}

	cfg := config.Default()
	cfg.Harnesses = make(map[string]config.HarnessConfig)
	for _, rt := range harnesses {
		cfg.Harnesses[rt] = config.HarnessConfig{Enabled: true}
	}
	cfg.Communication.Mode = "efficient"
	if err := config.Save(momDir, &cfg); err != nil {
		t.Fatalf("saving config: %v", err)
	}

	// Write minimal identity and schema so upgrade doesn't fail.
	os.WriteFile(filepath.Join(momDir, "identity.json"), []byte(`{"old": true}`), 0644)
	os.WriteFile(filepath.Join(momDir, "schema.json"), []byte(`{"old": true}`), 0644)
}

// ── Test 1: Init with all harnesses ──────────────────────────────────────────

func TestIntegration_InitAllHarnesses(t *testing.T) {
	dir := t.TempDir()
	home := t.TempDir()
	t.Setenv("HOME", home) // isolate global configs

	allHarnesses := []string{"claude", "codex", "pi"}
	initProject(t, dir, allHarnesses)

	// ── central .mom/ structure ──
	assertFileNotExists(t, filepath.Join(dir, ".mom"))
	assertFileExists(t, filepath.Join(home, ".mom", "config.yaml"))
	assertFileExists(t, filepath.Join(home, ".mom", "identity.json"))
	assertFileExists(t, filepath.Join(home, ".mom", "schema.json"))

	cfg, err := config.Load(filepath.Join(home, ".mom"))
	if err != nil {
		t.Fatalf("loading config: %v", err)
	}
	enabled := cfg.EnabledHarnesses()
	if len(enabled) != 3 {
		t.Errorf("expected 3 enabled harnesses, got %d: %v", len(enabled), enabled)
	}

	// ── Claude ──
	claudeMD := filepath.Join(home, ".claude", "CLAUDE.md")
	assertFileExists(t, claudeMD)
	assertFileContains(t, claudeMD, "Generated by MOM")

	settingsJSON := filepath.Join(home, ".claude", "settings.json")
	assertFileExists(t, settingsJSON)
	assertFileContains(t, settingsJSON, "mom watch --sweep")

	// ── Codex ──
	agentsMD := filepath.Join(home, ".codex", "AGENTS.md")
	assertFileExists(t, agentsMD)
	assertFileContains(t, agentsMD, "Generated by MOM")
	// config.toml enables Codex hooks (no MCP server — MCP was retired).
	assertFileContains(t, filepath.Join(home, ".codex", "config.toml"), "hooks = true")

	// ── Pi ──
	piAgents := filepath.Join(home, ".pi", "agent", "AGENTS.md")
	assertFileExists(t, piAgents)
	assertFileContains(t, piAgents, "Generated by MOM")
	// The pi-mom extension is installed via the Pi marketplace
	// (`pi install npm:pi-mom`), not embedded by MOM (per #255). In
	// tests where the `pi` CLI is absent, the install soft-fails and
	// no extension file is written — that's expected.

	// MCP was retired in v0.50 — MOM writes no .mcp.json at all.
	assertFileNotExists(t, filepath.Join(dir, ".mcp.json"))
}

// ── Test 2: Upgrade registers ALL harnesses (regression) ─────────────────────

func TestIntegration_UpgradeRegistersAllHarnesses(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("HOME", dir)

	allHarnesses := []string{"claude", "codex", "pi"}
	setupMinimalMom(t, dir, allHarnesses)

	// No harness artifacts exist yet — this simulates the bug scenario.
	assertFileNotExists(t, filepath.Join(dir, ".claude", "CLAUDE.md"))
	assertFileNotExists(t, filepath.Join(dir, "AGENTS.md"))
	// MOM no longer writes a project-local mom-tools.ts — the pi-mom
	// extension is a marketplace install (per #255). Nothing to assert
	// in the project tree.

	output := upgradeProject(t, dir)

	// ALL harnesses must be regenerated — not just Claude.
	for _, rt := range allHarnesses {
		if !strings.Contains(output, "harness "+rt+" context file regenerated") {
			t.Errorf("upgrade output missing regeneration for harness %s", rt)
		}
	}

	// ── Verify artifacts created for ALL harnesses ──
	assertFileExists(t, filepath.Join(dir, ".claude", "CLAUDE.md"))
	assertFileContains(t, filepath.Join(dir, ".claude", "CLAUDE.md"), "Generated by MOM")

	assertFileExists(t, filepath.Join(dir, ".claude", "settings.json"))
	assertFileContains(t, filepath.Join(dir, ".claude", "settings.json"), "mom watch --sweep")

	assertFileExists(t, filepath.Join(dir, "AGENTS.md"))
	assertFileExists(t, filepath.Join(dir, ".codex", "hooks.json"))
	assertFileContains(t, filepath.Join(dir, ".codex", "hooks.json"), "watch --sweep --global")

	// Pi extension is no longer embedded — it's installed via the Pi
	// marketplace at session level (`pi install npm:pi-mom`), not by
	// MOM's upgrade flow. AGENTS.md is the only project artifact MOM
	// writes for the pi harness.
}

// ── Test 3: Upgrade is local to the current filesystem project ─────────────

func TestIntegration_UpgradeDoesNotPropagateScopes(t *testing.T) {
	root := t.TempDir()
	t.Setenv("HOME", root)

	// Build hierarchy: root (user) → org-a (org) → repo-1, repo-2 (repos)
	orgDir := filepath.Join(root, "org-a")
	repo1 := filepath.Join(orgDir, "repo-1")
	repo2 := filepath.Join(orgDir, "repo-2")

	for _, d := range []string{repo1, repo2} {
		os.MkdirAll(filepath.Join(d, ".git"), 0755)
	}

	// Init .mom/ at each level with claude only.
	for _, pair := range []struct {
		dir   string
		scope string
	}{
		{root, "user"},
		{orgDir, "org"},
		{repo1, "repo"},
		{repo2, "repo"},
	} {
		momDir := filepath.Join(pair.dir, ".mom")
		os.MkdirAll(filepath.Join(momDir, "memory"), 0755)
		cfg := config.Default()
		cfg.Scope = pair.scope
		config.Save(momDir, &cfg)
		os.WriteFile(filepath.Join(momDir, "identity.json"), []byte(`{"old": true}`), 0644)
		os.WriteFile(filepath.Join(momDir, "schema.json"), []byte(`{"old": true}`), 0644)
	}

	upgradeProject(t, root)

	rootSchema, err := os.ReadFile(filepath.Join(root, ".mom", "schema.json"))
	if err != nil {
		t.Fatalf("missing root schema.json: %v", err)
	}
	if string(rootSchema) == `{"old": true}` {
		t.Fatal("root schema.json was not updated")
	}
	assertFileExists(t, filepath.Join(root, ".claude", "CLAUDE.md"))

	for _, d := range []string{orgDir, repo1, repo2} {
		schemaPath := filepath.Join(d, ".mom", "schema.json")
		data, err := os.ReadFile(schemaPath)
		if err != nil {
			t.Errorf("missing schema.json in %s", d)
			continue
		}
		if string(data) != `{"old": true}` {
			t.Errorf("schema.json unexpectedly updated in %s", d)
		}
	}
}

// ── Test 4: Add harnesses via upgrade ────────────────────────────────────────

func TestIntegration_AddHarnessesViaUpgrade(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("HOME", dir)

	// Set up a minimal .mom/ with claude only (avoids cobra flag leakage).
	setupMinimalMom(t, dir, []string{"claude"})

	// Claude artifacts do NOT exist yet (setupMinimalMom only creates config).
	assertFileNotExists(t, filepath.Join(dir, "AGENTS.md"))

	// Run upgrade to generate claude artifacts.
	upgradeProject(t, dir)

	// Claude artifacts should exist now.
	assertFileExists(t, filepath.Join(dir, ".claude", "CLAUDE.md"))
	// Codex should NOT exist yet (only claude is in config).
	assertFileNotExists(t, filepath.Join(dir, "AGENTS.md"))

	// Add codex to config.
	momDir := filepath.Join(dir, ".mom")
	cfg, _ := config.Load(momDir)
	cfg.Harnesses["codex"] = config.HarnessConfig{Enabled: true}
	config.Save(momDir, cfg)

	// Upgrade should pick up new harnesses.
	upgradeProject(t, dir)

	// Both should now exist.
	assertFileExists(t, filepath.Join(dir, ".claude", "CLAUDE.md"))
	assertFileExists(t, filepath.Join(dir, "AGENTS.md"))
	assertFileExists(t, filepath.Join(dir, ".codex", "hooks.json"))
}

// Test 5 (Record + Draft pipeline) was retired in #240 PR 3. The
// `mom draft` CLI command and its batch-processor surface are gone;
// drafting now happens via the watcher → bus → drafter clustering
// pipeline, which is integration-tested in workers/drafter.

// Tests 6 and 7 (MCP config correctness / custom MCP preservation) were
// retired in v0.50: MOM no longer ships an MCP server, and init/upgrade
// no longer write any mcpServers entries. Memory is delivered via the
// per-project markdown vault and the always-loaded context block.
