package harness

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestClaudeAdapter_Name(t *testing.T) {
	a := NewClaudeAdapter("/tmp/test")
	if a.Name() != "claude" {
		t.Errorf("expected %q, got %q", "claude", a.Name())
	}
}

func TestRemoveStaleClaudeMCP(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)

	// ~/.claude.json: top-level mcpServers.mom plus a per-project map, alongside
	// content that must survive untouched.
	claudeJSON := `{
  "numStartups": 7,
  "mcpServers": {"mom": {"command": "mom", "args": ["serve", "mcp"]}, "other": {"command": "x"}},
  "projects": {"/a": {"mcpServers": {"mom": {"command": "mom"}}, "history": ["k"]}}
}`
	mcpJSON := `{"mcpServers": {"mom": {"command": "mom"}}}`
	mustWrite(t, filepath.Join(home, ".claude.json"), claudeJSON)
	mustWrite(t, filepath.Join(home, ".mcp.json"), mcpJSON)

	changed, err := removeStaleClaudeMCP()
	if err != nil {
		t.Fatalf("removeStaleClaudeMCP: %v", err)
	}
	if len(changed) != 2 {
		t.Fatalf("expected 2 files rewritten, got %d (%v)", len(changed), changed)
	}

	got := readJSON(t, filepath.Join(home, ".claude.json"))
	servers := got["mcpServers"].(map[string]any)
	if _, ok := servers["mom"]; ok {
		t.Error("top-level mcpServers.mom not removed")
	}
	if _, ok := servers["other"]; !ok {
		t.Error("unrelated mcpServers.other was dropped")
	}
	if got["numStartups"].(float64) != 7 {
		t.Error("unrelated content not preserved")
	}
	proj := got["projects"].(map[string]any)["/a"].(map[string]any)
	if _, ok := proj["mcpServers"].(map[string]any)["mom"]; ok {
		t.Error("per-project mcpServers.mom not removed")
	}

	// Idempotent: a second run with no mom entries rewrites nothing.
	changed, err = removeStaleClaudeMCP()
	if err != nil {
		t.Fatalf("second run: %v", err)
	}
	if len(changed) != 0 {
		t.Errorf("expected no rewrites on clean configs, got %v", changed)
	}
}

func mustWrite(t *testing.T, path, content string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}
}

func readJSON(t *testing.T, path string) map[string]any {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	var m map[string]any
	if err := json.Unmarshal(data, &m); err != nil {
		t.Fatalf("unmarshal %s: %v", path, err)
	}
	return m
}

func TestClaudeAdapter_DetectHarness(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("PATH", t.TempDir())

	a := NewClaudeAdapter(t.TempDir())
	if a.DetectHarness() {
		t.Error("expected false when global Claude config does not exist")
	}

	os.MkdirAll(filepath.Join(home, ".claude"), 0755)
	if !a.DetectHarness() {
		t.Error("expected true when global .claude/ exists")
	}
}

func TestClaudeAdapter_GenerateContextFile(t *testing.T) {
	dir := t.TempDir()
	a := NewClaudeAdapter(dir)

	config := Config{
		Version: "1",
		User: UserConfig{
			Language:          "en",
			Autonomy:          "balanced",
			CommunicationMode: "concise",
		},
	}

	if err := a.GenerateContextFile(config, nil, nil, nil); err != nil {
		t.Fatalf("GenerateContextFile failed: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(dir, ".claude", "CLAUDE.md"))
	if err != nil {
		t.Fatalf("reading CLAUDE.md: %v", err)
	}

	s := string(content)
	checks := []string{
		"Generated by MOM",
		"MOM — Memory Oriented Machine",
		"mom project",
		".mom/vault/INDEX.md",
		"mom vault fold",
		"must be written in English",
		"## Communication mode: Concise",
		"Every word earns its place",
		"Balanced",
		"Propose before",
	}
	for _, check := range checks {
		if !strings.Contains(s, check) {
			t.Errorf("CLAUDE.md missing %q", check)
		}
	}
	// MCP must be gone from generated context.
	for _, bad := range []string{"mom_status", "MCP", ".mom/memory/"} {
		if strings.Contains(s, bad) {
			t.Errorf("CLAUDE.md must not contain %q", bad)
		}
	}
}

// TestClaudeAdapter_GenerateContextFile_NoProfile verifies that retired profile
// references (orchestrator, specialist, delegation) do NOT appear in generated output.
func TestClaudeAdapter_GenerateContextFile_NoProfile(t *testing.T) {
	dir := t.TempDir()
	a := NewClaudeAdapter(dir)

	config := Config{
		Version: "1",
		User:    UserConfig{Language: "en", Autonomy: "balanced", CommunicationMode: "concise"},
	}

	if err := a.GenerateContextFile(config, nil, nil, nil); err != nil {
		t.Fatalf("GenerateContextFile failed: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(dir, ".claude", "CLAUDE.md"))
	if err != nil {
		t.Fatalf("reading CLAUDE.md: %v", err)
	}

	s := string(content)
	// These phrases indicate the retired orchestration model — they must not appear.
	forbidden := []string{"specialist", "delegation", "task-intake", "Active Profile",
		"orchestrates, never executes", "mom orchestrates", "task pipeline"}
	for _, bad := range forbidden {
		if strings.Contains(strings.ToLower(s), strings.ToLower(bad)) {
			t.Errorf("CLAUDE.md must not contain %q", bad)
		}
	}
}

func TestClaudeAdapter_GenerateContextFile_NoIdentity(t *testing.T) {
	dir := t.TempDir()
	a := NewClaudeAdapter(dir)

	config := Config{
		Version: "1",
		User: UserConfig{
			Language: "en",
			Autonomy: "balanced",
		},
	}

	if err := a.GenerateContextFile(config, nil, nil, nil); err != nil {
		t.Fatalf("GenerateContextFile failed: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(dir, ".claude", "CLAUDE.md"))
	if err != nil {
		t.Fatalf("reading CLAUDE.md: %v", err)
	}

	s := string(content)
	// A nil identity must not break generation; the vault-first protocol
	// still renders.
	if !strings.Contains(s, ".mom/vault/INDEX.md") {
		t.Error("CLAUDE.md missing vault-first protocol")
	}
}

func TestClaudeAdapter_GenerateContextFile_CommunicationModes(t *testing.T) {
	modes := []struct {
		mode string
		want string
	}{
		{"concise", "## Communication mode: Concise"},
		{"efficient", "## Communication mode: Efficient"},
	}

	for _, tc := range modes {
		t.Run(tc.mode, func(t *testing.T) {
			dir := t.TempDir()
			a := NewClaudeAdapter(dir)
			cfg := Config{
				Version: "1",
				User:    UserConfig{Language: "en", Autonomy: "balanced", CommunicationMode: tc.mode},
			}
			if err := a.GenerateContextFile(cfg, nil, nil, nil); err != nil {
				t.Fatalf("GenerateContextFile failed: %v", err)
			}
			content, _ := os.ReadFile(filepath.Join(dir, ".claude", "CLAUDE.md"))
			if !strings.Contains(string(content), tc.want) {
				t.Errorf("CLAUDE.md missing %q for mode %q", tc.want, tc.mode)
			}
		})
	}

	// "default" mode returns empty instructions — no communication header in output.
	t.Run("default", func(t *testing.T) {
		dir := t.TempDir()
		a := NewClaudeAdapter(dir)
		cfg := Config{
			Version: "1",
			User:    UserConfig{Language: "en", Autonomy: "balanced", CommunicationMode: "default"},
		}
		if err := a.GenerateContextFile(cfg, nil, nil, nil); err != nil {
			t.Fatalf("GenerateContextFile failed: %v", err)
		}
		content, _ := os.ReadFile(filepath.Join(dir, ".claude", "CLAUDE.md"))
		if strings.Contains(string(content), "## Communication mode") {
			t.Error("CLAUDE.md should not contain communication mode header for default mode")
		}
	})
}

func TestClaudeAdapter_RegisterHooks(t *testing.T) {
	dir := t.TempDir()
	a := NewClaudeAdapter(dir)

	if err := a.RegisterHooks(); err != nil {
		t.Fatalf("RegisterHooks failed: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(dir, ".claude", "settings.json"))
	if err != nil {
		t.Fatalf("reading settings.json: %v", err)
	}

	var settings map[string]any
	if err := json.Unmarshal(content, &settings); err != nil {
		t.Fatalf("parsing settings.json: %v", err)
	}

	hooksMap, ok := settings["hooks"].(map[string]any)
	if !ok {
		t.Fatal("hooks should be a map")
	}

	stop, ok := hooksMap["Stop"].([]any)
	if !ok {
		t.Fatal("hooks.Stop should be an array")
	}
	if len(stop) != 1 {
		t.Fatalf("expected 1 Stop matcher group (sweep only), got %d", len(stop))
	}

	group0 := stop[0].(map[string]any)
	innerHooks0 := group0["hooks"].([]any)
	hookEntry0 := innerHooks0[0].(map[string]any)
	if hookEntry0["command"] != "mom watch --sweep" {
		t.Errorf("expected command 'mom watch --sweep', got %v", hookEntry0["command"])
	}

	// SessionEnd has a fallback sweep to catch the last response.
	sessionEnd, ok := hooksMap["SessionEnd"].([]any)
	if !ok {
		t.Fatal("hooks.SessionEnd should be an array")
	}
	if len(sessionEnd) != 1 {
		t.Fatalf("expected 1 SessionEnd matcher group (sweep), got %d", len(sessionEnd))
	}
	seGroup := sessionEnd[0].(map[string]any)
	seHooks := seGroup["hooks"].([]any)
	seEntry := seHooks[0].(map[string]any)
	if seEntry["command"] != "mom watch --sweep" {
		t.Errorf("expected SessionEnd command 'mom watch --sweep', got %v", seEntry["command"])
	}
}

func TestClaudeAdapter_Watermark(t *testing.T) {
	a := NewClaudeAdapter("/tmp/test")
	wm := a.Watermark()
	if !strings.Contains(wm, "Generated by MOM") {
		t.Errorf("expected watermark to contain 'Generated by MOM', got %q", wm)
	}
}

func TestWatermarkPresent(t *testing.T) {
	dir := t.TempDir()
	a := NewClaudeAdapter(dir)

	config := Config{Version: "1", User: UserConfig{Language: "en", Autonomy: "balanced"}}

	if err := a.GenerateContextFile(config, nil, nil, nil); err != nil {
		t.Fatalf("GenerateContextFile failed: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(dir, ".claude", "CLAUDE.md"))
	if err != nil {
		t.Fatal(err)
	}

	if !strings.HasPrefix(string(content), "<!-- Generated by MOM") {
		t.Error("generated file should start with watermark")
	}
}

func TestBackupCreatedForUserFile(t *testing.T) {
	dir := t.TempDir()
	userFile := filepath.Join(dir, "CLAUDE.md")
	os.WriteFile(userFile, []byte("# My custom rules"), 0644)

	backed, err := BackupIfNeeded(userFile)
	if err != nil {
		t.Fatalf("BackupIfNeeded failed: %v", err)
	}
	if !backed {
		t.Error("expected backup to be created for user file")
	}

	bkpContent, err := os.ReadFile(userFile + ".bkp")
	if err != nil {
		t.Fatal("backup file not created")
	}
	if string(bkpContent) != "# My custom rules" {
		t.Error("backup content doesn't match original")
	}
}

func TestNoBackupForLeoFile(t *testing.T) {
	dir := t.TempDir()
	leoFile := filepath.Join(dir, "CLAUDE.md")
	os.WriteFile(leoFile, []byte("<!-- Generated by MOM — do not edit manually -->\n# MOM"), 0644)

	backed, err := BackupIfNeeded(leoFile)
	if err != nil {
		t.Fatalf("BackupIfNeeded failed: %v", err)
	}
	if backed {
		t.Error("should not backup MOM-generated file")
	}
}

func TestBackupNonexistentFile(t *testing.T) {
	backed, err := BackupIfNeeded("/nonexistent/path")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if backed {
		t.Error("should not backup nonexistent file")
	}
}
