package harness

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestDroidAdapter_Name(t *testing.T) {
	a := NewDroidAdapter("/tmp/test")
	if a.Name() != "droid" {
		t.Errorf("expected %q, got %q", "droid", a.Name())
	}
}

func TestDroidAdapter_Tier(t *testing.T) {
	a := NewDroidAdapter("/tmp/test")
	if a.Tier() != Fluent {
		t.Errorf("expected Fluent tier, got %v", a.Tier())
	}
}

func TestDroidAdapter_DefaultTranscriptDir(t *testing.T) {
	a := NewDroidAdapter("/tmp")
	if got := a.DefaultTranscriptDir(); got != "~/.factory/sessions/" {
		t.Errorf("DefaultTranscriptDir = %q, want ~/.factory/sessions/", got)
	}
}

func TestDroidAdapter_DetectHarness(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("PATH", t.TempDir())
	a := NewDroidAdapter(t.TempDir())

	if a.DetectHarness() {
		t.Error("expected false when global Droid config does not exist")
	}

	os.MkdirAll(filepath.Join(home, ".factory"), 0755)
	if !a.DetectHarness() {
		t.Error("expected true when global .factory/ exists")
	}
}

func TestDroidAdapter_GenerateContextFile(t *testing.T) {
	dir := t.TempDir()
	a := NewDroidAdapter(dir)

	config := Config{
		Version: "1",
		User:    UserConfig{Language: "en", Autonomy: "balanced", CommunicationMode: "concise"},
	}

	if err := a.GenerateContextFile(config, nil, nil, nil); err != nil {
		t.Fatalf("GenerateContextFile failed: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(dir, "AGENTS.md"))
	if err != nil {
		t.Fatalf("reading AGENTS.md: %v", err)
	}

	s := string(content)
	checks := []string{
		"Generated by MOM",
		"MOM — Memory Oriented Machine",
		"mom project",
		".mom/vault/INDEX.md",
	}
	for _, check := range checks {
		if !strings.Contains(s, check) {
			t.Errorf("AGENTS.md missing %q", check)
		}
	}
}

func TestDroidAdapter_RegisterHooks(t *testing.T) {
	dir := t.TempDir()
	a := NewDroidAdapter(dir)

	if err := a.RegisterHooks(); err != nil {
		t.Fatalf("RegisterHooks failed: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(dir, ".factory", "settings.json"))
	if err != nil {
		t.Fatalf("reading settings.json: %v", err)
	}

	var settings map[string]any
	if err := json.Unmarshal(content, &settings); err != nil {
		t.Fatalf("parsing settings.json: %v", err)
	}

	hooksMap, ok := settings["hooks"].(map[string]any)
	if !ok {
		t.Fatal("hooks should be a map")
	}

	stop, ok := hooksMap["Stop"].([]any)
	if !ok || len(stop) != 1 {
		t.Fatalf("expected 1 Stop matcher group, got %v", hooksMap["Stop"])
	}
	group := stop[0].(map[string]any)
	inner := group["hooks"].([]any)
	entry := inner[0].(map[string]any)
	if entry["command"] != "mom watch --sweep" {
		t.Errorf("expected command 'mom watch --sweep', got %v", entry["command"])
	}

	sessionEnd, ok := hooksMap["SessionEnd"].([]any)
	if !ok || len(sessionEnd) != 1 {
		t.Fatalf("expected 1 SessionEnd matcher group, got %v", hooksMap["SessionEnd"])
	}
}

// RegisterHooks must merge into an existing settings.json rather than
// overwrite it — a real Droid install already has unrelated keys
// (model, autonomyMode, etc.) that must survive.
func TestDroidAdapter_RegisterHooks_PreservesExisting(t *testing.T) {
	dir := t.TempDir()
	factoryDir := filepath.Join(dir, ".factory")
	os.MkdirAll(factoryDir, 0755)
	existing := `{"model": "claude-opus-4-5", "autonomyMode": "auto-high"}`
	if err := os.WriteFile(filepath.Join(factoryDir, "settings.json"), []byte(existing), 0644); err != nil {
		t.Fatal(err)
	}

	a := NewDroidAdapter(dir)
	if err := a.RegisterHooks(); err != nil {
		t.Fatalf("RegisterHooks failed: %v", err)
	}

	data, _ := os.ReadFile(filepath.Join(factoryDir, "settings.json"))
	var settings map[string]any
	if err := json.Unmarshal(data, &settings); err != nil {
		t.Fatalf("parsing settings.json: %v", err)
	}
	if settings["model"] != "claude-opus-4-5" {
		t.Errorf("expected existing model key preserved, got %v", settings["model"])
	}
	if _, ok := settings["hooks"]; !ok {
		t.Error("expected hooks key to be added")
	}
}

func TestDroidAdapter_RegisterGlobalHooks_WritesToHomeFactoryDir(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	a := NewDroidAdapter("/tmp/unused-project-root")

	if err := a.RegisterGlobalHooks(); err != nil {
		t.Fatalf("RegisterGlobalHooks: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(home, ".factory", "settings.json"))
	if err != nil {
		t.Fatalf("reading global settings.json: %v", err)
	}
	var root map[string]any
	if err := json.Unmarshal(data, &root); err != nil {
		t.Fatalf("parse settings.json: %v", err)
	}
	if _, ok := root["hooks"].(map[string]any); !ok {
		t.Fatal("missing top-level 'hooks' key")
	}
}

func TestDroidAdapter_GeneratedFiles(t *testing.T) {
	a := NewDroidAdapter("/tmp/test")
	files := a.GeneratedFiles()
	expected := []string{"AGENTS.md", filepath.Join(".factory", "settings.json")}
	if len(files) != len(expected) {
		t.Fatalf("expected %d files, got %d: %v", len(expected), len(files), files)
	}
	for i, f := range files {
		if f != expected[i] {
			t.Errorf("expected files[%d] = %q, got %q", i, expected[i], f)
		}
	}
}

func TestDroidAdapter_GeneratedDirs(t *testing.T) {
	a := NewDroidAdapter("/tmp/test")
	dirs := a.GeneratedDirs()
	if len(dirs) != 1 || dirs[0] != ".factory" {
		t.Errorf("expected [.factory], got %v", dirs)
	}
}

func TestDroidAdapter_Capabilities(t *testing.T) {
	a := NewDroidAdapter("/tmp/test")
	cap := a.Capabilities()
	if cap.Name != "droid" {
		t.Errorf("expected capability name 'droid', got %q", cap.Name)
	}
}
