package harness

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestPiAdapter_Name(t *testing.T) {
	if got := NewPiAdapter("/tmp/x").Name(); got != "pi" {
		t.Errorf("Name(): got %q, want pi", got)
	}
}

func TestPiAdapter_GenerateContextFile(t *testing.T) {
	dir := t.TempDir()
	a := NewPiAdapter(dir)

	cfg := Config{
		Version: "1",
		User: UserConfig{
			Language:          "en",
			Autonomy:          "balanced",
			CommunicationMode: "concise",
		},
	}

	if err := a.GenerateContextFile(cfg, nil, nil, nil); err != nil {
		t.Fatalf("GenerateContextFile: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(dir, "AGENTS.md"))
	if err != nil {
		t.Fatalf("reading AGENTS.md: %v", err)
	}
	s := string(content)
	if !strings.Contains(s, "Generated by MOM") {
		t.Error("AGENTS.md missing watermark")
	}
	if !strings.Contains(s, ".mom/vault/INDEX.md") {
		t.Error("AGENTS.md missing vault-first protocol")
	}
	if strings.Contains(s, "MCP") || strings.Contains(s, "mom_status") {
		t.Errorf("AGENTS.md must not reference MCP:\n%s", s)
	}
}

// TestPiAdapter_RegisterGlobalExtension_InvokesPiMarketplace verifies
// that RegisterGlobalExtension shells the Pi marketplace install
// command per #255 — the embedded TypeScript surface is retired.
func TestPiAdapter_RegisterGlobalExtension_InvokesPiMarketplace(t *testing.T) {
	// Stub the install command so the test does not require pi on PATH.
	origInstall := piInstallCommand
	origLookPath := commandExistsForPi
	t.Cleanup(func() {
		piInstallCommand = origInstall
		commandExistsForPi = origLookPath
	})
	commandExistsForPi = func() bool { return true }

	var capturedPkg string
	piInstallCommand = func(pkg string) ([]byte, error) {
		capturedPkg = pkg
		return []byte("ok"), nil
	}

	a := NewPiAdapter(t.TempDir())
	if err := a.RegisterGlobalExtension(); err != nil {
		t.Fatalf("RegisterGlobalExtension: %v", err)
	}
	if capturedPkg != "npm:pi-mom" {
		t.Errorf("install package = %q, want npm:pi-mom", capturedPkg)
	}
}

// When pi is not on PATH, RegisterGlobalExtension surfaces an actionable
// error (caller — mom init — soft-fails to the user).
func TestPiAdapter_RegisterGlobalExtension_FailsWhenPiMissing(t *testing.T) {
	origLookPath := commandExistsForPi
	t.Cleanup(func() { commandExistsForPi = origLookPath })
	commandExistsForPi = func() bool { return false }

	a := NewPiAdapter(t.TempDir())
	err := a.RegisterGlobalExtension()
	if err == nil {
		t.Fatal("expected error when pi CLI is missing")
	}
	if !strings.Contains(err.Error(), "pi CLI not found") {
		t.Errorf("error should mention missing pi CLI, got %v", err)
	}
}

// Install command failures surface as errors with the underlying output
// so users (and mom init's logger) can diagnose.
func TestPiAdapter_RegisterGlobalExtension_SurfacesInstallError(t *testing.T) {
	origInstall := piInstallCommand
	origLookPath := commandExistsForPi
	t.Cleanup(func() {
		piInstallCommand = origInstall
		commandExistsForPi = origLookPath
	})
	commandExistsForPi = func() bool { return true }
	piInstallCommand = func(pkg string) ([]byte, error) {
		return []byte("network unreachable"), fmt.Errorf("exit status 1")
	}

	a := NewPiAdapter(t.TempDir())
	err := a.RegisterGlobalExtension()
	if err == nil {
		t.Fatal("expected install error to surface")
	}
	if !strings.Contains(err.Error(), "network unreachable") {
		t.Errorf("error should surface install output, got %v", err)
	}
}

func TestPiAdapter_DetectHarness(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("PATH", t.TempDir())
	a := NewPiAdapter(t.TempDir())

	if a.DetectHarness() {
		t.Error("expected false when global pi config absent")
	}

	if err := os.MkdirAll(filepath.Join(home, ".pi", "agent"), 0755); err != nil {
		t.Fatal(err)
	}
	if !a.DetectHarness() {
		t.Error("expected true when global pi config exists")
	}
}

func TestPiAdapter_DetectHarness_DoesNotMatchOnAGENTSMd(t *testing.T) {
	t.Setenv("HOME", t.TempDir())
	t.Setenv("PATH", t.TempDir())
	// Codex also writes AGENTS.md. Pi must NOT report itself as detected
	// based on AGENTS.md alone, otherwise every Codex project would
	// spuriously claim pi.
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "AGENTS.md"), []byte("..."), 0644); err != nil {
		t.Fatal(err)
	}
	if NewPiAdapter(dir).DetectHarness() {
		t.Error("AGENTS.md alone must not trigger pi detection")
	}
}

func TestPiAdapter_GeneratedFiles(t *testing.T) {
	a := NewPiAdapter("/tmp/x")
	got := a.GeneratedFiles()
	// The pi-mom extension is installed via the Pi marketplace into
	// ~/.pi/agent/extensions/ (see RegisterGlobalExtension) — it is
	// not a MOM-generated project file. Only AGENTS.md lands in the
	// project root.
	want := []string{
		"AGENTS.md",
	}
	if len(got) != len(want) {
		t.Fatalf("len: got %d, want %d", len(got), len(want))
	}
	for i := range want {
		if got[i] != want[i] {
			t.Errorf("file[%d]: got %q, want %q", i, got[i], want[i])
		}
	}
}

func TestPiAdapter_GeneratedDirs(t *testing.T) {
	a := NewPiAdapter("/tmp/x")
	got := a.GeneratedDirs()
	if len(got) != 1 || got[0] != ".pi" {
		t.Errorf("GeneratedDirs: got %v, want [.pi]", got)
	}
}

func TestPiAdapter_Watermark(t *testing.T) {
	a := NewPiAdapter("/tmp/x")
	if !strings.Contains(a.Watermark(), "Generated by MOM") {
		t.Errorf("watermark: %q", a.Watermark())
	}
}

// TestPiAdapter_Capabilities lives in capabilities_test.go alongside the
// other adapters' capability tests — keeping the cross-Harness contract
// (Supports vs Experimental, no overlap) in one place.
